# Generated by Django 6.0.1 on 2026-03-10 16:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0032_alter_productbundle_name_and_more'),
        ('orders', '0013_order_v1_checkout_and_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_number', models.CharField(max_length=120, unique=True, verbose_name='Номер груза')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('in_transit', 'В пути в РФ'), ('arrived_rf', 'Прибыл в РФ'), ('delivery_rf', 'Доставка по РФ'), ('awaiting_receipt', 'Ожидает приемки'), ('received', 'Принят'), ('cancelled', 'Отменен')], db_index=True, default='created', max_length=32, verbose_name='Статус')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='Поставщик')),
                ('agent', models.CharField(blank=True, max_length=255, verbose_name='Агент')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ordered', 'Заказано'), ('partial', 'Частично получено'), ('received', 'Получено'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('currency', models.CharField(default='CNY', max_length=12, verbose_name='Валюта')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='Принято')),
                ('arrival_photo', models.ImageField(blank=True, upload_to='manager/cargo-items/', verbose_name='Фото приемки')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manager_portal.cargo', verbose_name='Груз')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_cargo_items', to='catalog.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_cargo_items', to='catalog.productvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Позиция груза',
                'verbose_name_plural': 'Позиции груза',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CargoPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manager/cargos/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='manager_portal.cargo', verbose_name='Груз')),
            ],
            options={
                'verbose_name': 'Фото груза',
                'verbose_name_plural': 'Фото грузов',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ManagerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя / компания')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=120, verbose_name='Telegram')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('archived', 'Архив')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('orders', models.ManyToManyField(blank=True, related_name='manager_client_links', to='orders.order', verbose_name='Связанные заказы сайта')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_clients', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь сайта')),
            ],
            options={
                'verbose_name': 'Внутренний клиент',
                'verbose_name_plural': 'Внутренние клиенты',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='manager_portal.purchase', verbose_name='Закупка'),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Цена')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='Получено')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приемки')),
                ('arrival_photo', models.ImageField(blank=True, upload_to='manager/purchases/', verbose_name='Фото приемки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_purchase_items', to='catalog.product', verbose_name='Товар')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manager_portal.purchase', verbose_name='Закупка')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_purchase_items', to='catalog.productvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Позиция закупки',
                'verbose_name_plural': 'Позиции закупки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransportLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255, verbose_name='Откуда')),
                ('method', models.CharField(blank=True, max_length=120, verbose_name='Метод')),
                ('track_number', models.CharField(blank=True, max_length=120, verbose_name='Трек')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('in_transit', 'В пути'), ('arrived', 'Прибыл'), ('cancelled', 'Отменен')], default='created', max_length=20, verbose_name='Статус')),
                ('departed_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='Прибыл')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='manager_portal.cargo', verbose_name='Груз')),
            ],
            options={
                'verbose_name': 'Этап перевозки',
                'verbose_name_plural': 'Этапы перевозки',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='manager_portal.cargo', verbose_name='Груз')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='manager_portal.transportleg', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_warehouses', to='catalog.pickuppoint', verbose_name='Публичная точка выдачи')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='transportleg',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_legs', to='manager_portal.warehouse', verbose_name='Куда'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активно'), ('partial', 'Частично выдано'), ('fulfilled', 'Выполнено'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('source_type', models.CharField(choices=[('warehouse', 'Со склада'), ('cargo', 'Из груза')], max_length=20, verbose_name='Источник')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='manager_portal.managerclient', verbose_name='Клиент')),
                ('linked_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reservations', to='orders.order', verbose_name='Заказ сайта')),
                ('source_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_reservations', to='manager_portal.cargo', verbose_name='Груз-источник')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_reservations', to='manager_portal.warehouse', verbose_name='Склад-источник')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_reservations', to='manager_portal.warehouse', verbose_name='Склад назначения')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receipt', 'Приемка'), ('adjustment', 'Корректировка'), ('reserve', 'Резерв'), ('release', 'Снятие резерва')], max_length=20, verbose_name='Тип движения')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('reference_type', models.CharField(blank=True, max_length=40, verbose_name='Тип документа')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID документа')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_inventory_movements', to='catalog.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_inventory_movements', to='catalog.productvariant', verbose_name='Вариант')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='manager_portal.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Движение по складу',
                'verbose_name_plural': 'Движения по складу',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_cargos', to='manager_portal.warehouse', verbose_name='Склад назначения'),
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_reservation_items', to='catalog.product', verbose_name='Товар')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manager_portal.reservation', verbose_name='Бронь')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_reservation_items', to='catalog.productvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Позиция брони',
                'verbose_name_plural': 'Позиции брони',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('reservation', 'product'), name='manager_reservation_item_unique_without_variant'), models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('reservation', 'product', 'variant'), name='manager_reservation_item_unique_with_variant')],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_inventory_balances', to='catalog.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_inventory_balances', to='catalog.productvariant', verbose_name='Вариант')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='manager_portal.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Остаток склада',
                'verbose_name_plural': 'Остатки складов',
                'ordering': ['warehouse', 'product', 'variant'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('warehouse', 'product'), name='manager_balance_unique_without_variant'), models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('warehouse', 'product', 'variant'), name='manager_balance_unique_with_variant')],
            },
        ),
    ]
