# Generated by Django 6.0.1 on 2026-03-10 19:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_finance_dictionaries(apps, schema_editor):
    FinanceDealType = apps.get_model('manager_portal', 'FinanceDealType')
    FinanceExpenseCategory = apps.get_model('manager_portal', 'FinanceExpenseCategory')

    for name, share in (
        ('Партнерская', Decimal('0.5')),
        ('Трейд-ин / Из наличия', Decimal('0.3')),
        ('Моя личная', Decimal('0')),
    ):
        FinanceDealType.objects.get_or_create(
            name=name,
            defaults={'partner_share': share, 'is_active': True},
        )

    for side, names in (
        (
            'ours',
            (
                'Расходники',
                'Транспортировка',
                'Транспортные расходы',
                'CDEK',
                'TradeIn',
            ),
        ),
        (
            'partner',
            (
                'Оплата менеджеру',
                'Связь',
                'Учетные записи и программа для работы',
            ),
        ),
    ):
        for name in names:
            FinanceExpenseCategory.objects.get_or_create(
                expense_side=side,
                name=name,
                defaults={'is_active': True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('manager_portal', '0002_managerdeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceDealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Тип сделки')),
                ('partner_share', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5, verbose_name='Доля партнера')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Финансы: тип сделки',
                'verbose_name_plural': 'Финансы: типы сделок',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Дата сделки')),
                ('contract_number', models.CharField(blank=True, max_length=255, verbose_name='Договор / клиент')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Выручка')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Закуп / себестоимость')),
                ('direct_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Прямые расходы')),
                ('manager_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Бонус менеджера')),
                ('margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Маржа')),
                ('partner_share_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Доля партнера')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_finance_deals', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('deal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='manager_portal.financedealtype', verbose_name='Тип сделки')),
            ],
            options={
                'verbose_name': 'Финансы: сделка',
                'verbose_name_plural': 'Финансы: сделки',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_side', models.CharField(choices=[('ours', 'Наши'), ('partner', 'Партнера')], db_index=True, max_length=20, verbose_name='Сторона расхода')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Финансы: категория расхода',
                'verbose_name_plural': 'Финансы: категории расходов',
                'ordering': ['expense_side', 'name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('expense_side', 'name'), name='manager_finance_expense_category_side_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='FinanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_side', models.CharField(choices=[('ours', 'Наши'), ('partner', 'Партнера')], db_index=True, max_length=20, verbose_name='Сторона расхода')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('who_paid', models.CharField(blank=True, max_length=255, verbose_name='Кто оплатил')),
                ('partner_expense_share', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Доля партнера в расходе')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_finance_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='manager_portal.financedeal', verbose_name='Сделка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='manager_portal.financeexpensecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Финансы: расход',
                'verbose_name_plural': 'Финансы: расходы',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_finance_payouts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Финансы: выплата',
                'verbose_name_plural': 'Финансы: выплаты',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.RunPython(seed_finance_dictionaries, migrations.RunPython.noop),
    ]
