# Generated by Django 6.0.1 on 2026-03-10 20:38

import json
import sqlite3
from datetime import datetime, time, timezone as dt_timezone
from pathlib import Path

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils.dateparse import parse_date, parse_datetime


LEGACY_CONTRACT_TYPE_MAP = {
    'Договор оказания услуг': 'contract',
    'Договор поставки': 'contract',
}
LEGACY_CONTRACT_STATUS_MAP = {
    'Черновик': 'draft',
}
LEGACY_INVOICE_STATUS_MAP = {
    'Не оплачен': 'sent',
}


def _legacy_db_path():
    return Path(__file__).resolve().parents[2] / 'docuflow (2)' / 'server' / 'data.sqlite'


def _load_json(value, default):
    if not value:
        return default
    try:
        return json.loads(value)
    except Exception:
        return default


def _parse_legacy_date(value):
    if not value:
        return None
    value = str(value).strip()
    parsed = parse_date(value)
    if parsed:
        return parsed
    try:
        return datetime.strptime(value, '%d.%m.%Y').date()
    except ValueError:
        return None


def _parse_legacy_datetime(value):
    if not value:
        return None
    value = str(value).strip()
    parsed = parse_datetime(value.replace('Z', '+00:00'))
    if parsed:
        return parsed
    parsed_date = _parse_legacy_date(value)
    if parsed_date:
        return datetime.combine(parsed_date, time.min, tzinfo=dt_timezone.utc)
    return None


def import_docuflow_legacy_data(apps, schema_editor):
    legacy_db = _legacy_db_path()
    if not legacy_db.exists():
        return

    ContractCompanyProfile = apps.get_model('manager_portal', 'ContractCompanyProfile')
    ContractTemplate = apps.get_model('manager_portal', 'ContractTemplate')
    ContractDocument = apps.get_model('manager_portal', 'ContractDocument')

    conn = sqlite3.connect(f'file:{legacy_db}?mode=ro', uri=True)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    cur.execute('SELECT payload_json FROM app_settings WHERE id = 1')
    settings_row = cur.fetchone()
    settings_payload = _load_json(settings_row['payload_json'], {}) if settings_row else {}

    profile_map = {}
    raw_profiles = settings_payload.get('companyProfiles') or []
    active_profile_id = settings_payload.get('activeCompanyProfileId')
    if not raw_profiles and settings_payload:
        raw_profiles = [settings_payload]
    for index, raw_profile in enumerate(raw_profiles):
        external_id = raw_profile.get('id') or f'legacy-profile-{index + 1}'
        profile, _ = ContractCompanyProfile.objects.update_or_create(
            external_id=external_id,
            defaults={
                'name': raw_profile.get('companyName') or raw_profile.get('fullName') or f'Профиль {index + 1}',
                'legal_type': raw_profile.get('legalType') or 'other',
                'company_name': raw_profile.get('companyName') or raw_profile.get('fullName') or f'Профиль {index + 1}',
                'inn': raw_profile.get('inn', ''),
                'kpp': raw_profile.get('kpp', ''),
                'ogrn': raw_profile.get('ogrn', ''),
                'ogrnip': raw_profile.get('ogrnip', ''),
                'director_genitive': raw_profile.get('directorGenitive', ''),
                'legal_address': raw_profile.get('legalAddress', ''),
                'email': raw_profile.get('email', ''),
                'phone': raw_profile.get('phone', ''),
                'bank_name': raw_profile.get('bankName', ''),
                'checking_account': raw_profile.get('checkingAccount', ''),
                'correspondent_account': raw_profile.get('correspondentAccount', ''),
                'bik': raw_profile.get('bik', ''),
                'card_number': raw_profile.get('cardNumber', ''),
                'sbp_phone': raw_profile.get('sbpPhone', ''),
                'passport_series': raw_profile.get('passportSeries', ''),
                'passport_number': raw_profile.get('passportNumber', ''),
                'passport_issued_by': raw_profile.get('passportIssuedBy', ''),
                'passport_issued_date': _parse_legacy_date(raw_profile.get('passportIssuedDate')),
                'passport_department_code': raw_profile.get('passportDepartmentCode', ''),
                'registration_address': raw_profile.get('registrationAddress', ''),
                'residence_address': raw_profile.get('residenceAddress', ''),
                'bank_accounts': raw_profile.get('bankAccounts') or [],
                'legacy_payload': raw_profile,
                'is_active': external_id == active_profile_id or (not active_profile_id and index == 0),
            },
        )
        profile_map[external_id] = profile

    cur.execute('SELECT * FROM templates ORDER BY sort_order, id')
    template_map = {}
    for row in cur.fetchall():
        template, _ = ContractTemplate.objects.update_or_create(
            external_id=row['id'],
            defaults={
                'sort_order': row['sort_order'] or 0,
                'name': row['name'],
                'document_type': LEGACY_CONTRACT_TYPE_MAP.get(row['type'], 'other'),
                'version': row['version'] or '1.0',
                'description': f'Импортировано из legacy DocuFlow ({row["type"]})',
                'is_active': bool(row['is_active']),
                'content_html': row['content_html'] or '',
                'css_text': row['css_text'] or '',
                'variables_schema': _load_json(row['variables_json'], []),
                'created_at': _parse_legacy_datetime(row['updated_at']) or django.utils.timezone.now(),
                'updated_at': _parse_legacy_datetime(row['updated_at']) or django.utils.timezone.now(),
            },
        )
        template_map[row['id']] = template

    cur.execute('SELECT * FROM counterparties')
    counterparties = {row['id']: dict(row) for row in cur.fetchall()}

    cur.execute('SELECT * FROM invoices')
    invoices = {row['id']: dict(row) for row in cur.fetchall()}
    invoices_in_contracts = set()

    cur.execute('SELECT * FROM contracts ORDER BY sort_order, id')
    for row in cur.fetchall():
        counterparty_data = _load_json(row['counterparty_json'], {})
        contract_data = _load_json(row['contract_data_json'], {})
        invoice_payload = invoices.get(row['invoice_id'])
        if row['invoice_id']:
            invoices_in_contracts.add(row['invoice_id'])
        issue_dt = _parse_legacy_datetime(row['created_at']) or django.utils.timezone.now()
        company_profile = profile_map.get(row['supplier_profile_id']) or next(iter(profile_map.values()), None)
        ContractDocument.objects.update_or_create(
            external_id=row['id'],
            defaults={
                'source': 'imported_docuflow',
                'sort_order': row['sort_order'] or 0,
                'number': row['number'] or '',
                'title': row['title'] or '',
                'document_type': LEGACY_CONTRACT_TYPE_MAP.get(row['type'], 'contract'),
                'status': LEGACY_CONTRACT_STATUS_MAP.get(row['status'], 'draft'),
                'template': template_map.get(row['template_id']),
                'company_profile': company_profile,
                'issue_date': issue_dt.date(),
                'amount': Decimal(str(row['amount'])) if row['amount'] is not None else None,
                'payment_terms': row['payment_terms'],
                'include_delivery': bool(row['include_delivery']),
                'delivery_date': _parse_legacy_date(row['delivery_date']),
                'vat_rate': row['vat_rate'] or 'none',
                'vat_mode': row['vat_mode'] or 'included',
                'markup_percent': Decimal(str(row['markup_percent'] if row['markup_percent'] is not None else 6)),
                'markup_mode': row['markup_mode'] or 'per_item',
                'markup_calc_mode': row['markup_calc_mode'] or 'simple',
                'subject': contract_data.get('subject', ''),
                'counterparty_name': counterparty_data.get('name', ''),
                'counterparty_email': counterparty_data.get('email', ''),
                'counterparty_phone': counterparty_data.get('phone', ''),
                'counterparty_inn': counterparty_data.get('inn', ''),
                'counterparty_kpp': counterparty_data.get('kpp', ''),
                'counterparty_ogrn': counterparty_data.get('ogrn', ''),
                'counterparty_ogrnip': counterparty_data.get('ogrnip', ''),
                'counterparty_address': counterparty_data.get('address', ''),
                'counterparty_data': counterparty_data,
                'document_data': contract_data,
                'invoice_data': invoice_payload or {},
                'html_snapshot': row['html_snapshot'] or '',
                'snapshot_css': row['snapshot_css'] or '',
                'notes': 'Импортировано из legacy DocuFlow',
                'created_at': issue_dt,
                'updated_at': issue_dt,
            },
        )

    for invoice_id, row in invoices.items():
        if invoice_id in invoices_in_contracts:
            continue
        counterparty_data = counterparties.get(row['counterparty_id'], {})
        issue_date = _parse_legacy_date(row['date']) or django.utils.timezone.localdate()
        issue_dt = datetime.combine(issue_date, time.min, tzinfo=dt_timezone.utc)
        ContractDocument.objects.update_or_create(
            external_id=invoice_id,
            defaults={
                'source': 'imported_docuflow',
                'sort_order': row['sort_order'] or 0,
                'number': row['number'] or '',
                'title': f'Счет {row["number"]}',
                'document_type': 'invoice',
                'status': LEGACY_INVOICE_STATUS_MAP.get(row['status'], 'draft'),
                'company_profile': profile_map.get(row['supplier_profile_id']) or next(iter(profile_map.values()), None),
                'issue_date': issue_date,
                'amount': Decimal(str(row['amount'])) if row['amount'] is not None else None,
                'currency': row['currency'] or 'RUB',
                'payment_terms': None,
                'vat_rate': row['vat_rate'] or 'none',
                'vat_mode': row['vat_mode'] or 'included',
                'subject': 'Импортированный счет из legacy DocuFlow',
                'counterparty_name': counterparty_data.get('name', ''),
                'counterparty_email': counterparty_data.get('email', ''),
                'counterparty_phone': counterparty_data.get('phone', ''),
                'counterparty_inn': counterparty_data.get('inn', ''),
                'counterparty_kpp': counterparty_data.get('kpp', ''),
                'counterparty_ogrn': counterparty_data.get('ogrn', ''),
                'counterparty_ogrnip': counterparty_data.get('ogrnip', ''),
                'counterparty_address': counterparty_data.get('address', ''),
                'counterparty_data': counterparty_data,
                'document_data': {},
                'invoice_data': {
                    'items': _load_json(row['items_json'], []),
                    'commission_percent': row['commission_percent'],
                    'payment_due_date': row['payment_due_date'],
                },
                'html_snapshot': '',
                'snapshot_css': '',
                'notes': 'Импортировано из legacy DocuFlow',
                'created_at': issue_dt,
                'updated_at': issue_dt,
            },
        )

    conn.close()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_product_shipping_height_cm_and_more'),
        ('manager_portal', '0004_managerdeal_scenarios_and_tradeinitem'),
        ('orders', '0015_orderitem_comment_orderitem_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Legacy ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название профиля')),
                ('legal_type', models.CharField(choices=[('ooo', 'ООО'), ('ip', 'ИП'), ('person', 'Физ. лицо'), ('other', 'Другое')], default='ip', max_length=20, verbose_name='Тип лица')),
                ('company_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН')),
                ('ogrnip', models.CharField(blank=True, max_length=20, verbose_name='ОГРНИП')),
                ('director_genitive', models.CharField(blank=True, max_length=255, verbose_name='Подписант (род. падеж)')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('checking_account', models.CharField(blank=True, max_length=64, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(blank=True, max_length=64, verbose_name='Корр. счет')),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('card_number', models.CharField(blank=True, max_length=40, verbose_name='Номер карты')),
                ('sbp_phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон СБП')),
                ('passport_series', models.CharField(blank=True, max_length=20, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан')),
                ('passport_issued_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('passport_department_code', models.CharField(blank=True, max_length=20, verbose_name='Код подразделения')),
                ('registration_address', models.TextField(blank=True, verbose_name='Адрес регистрации')),
                ('residence_address', models.TextField(blank=True, verbose_name='Адрес проживания')),
                ('bank_accounts', models.JSONField(blank=True, default=list, verbose_name='Банковские счета')),
                ('legacy_payload', models.JSONField(blank=True, default=dict, verbose_name='Legacy payload')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Профиль договоров',
                'verbose_name_plural': 'Профили договоров',
                'ordering': ['-is_active', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Legacy ID')),
                ('source', models.CharField(choices=[('internal', 'Внутренний кабинет'), ('imported_docuflow', 'Импортировано из DocuFlow')], default='internal', max_length=30, verbose_name='Источник')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Номер документа')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('document_type', models.CharField(choices=[('contract', 'Договор'), ('invoice', 'Счет'), ('act', 'Акт'), ('appendix', 'Приложение'), ('offer', 'Оферта / КП'), ('other', 'Другое')], db_index=True, default='contract', max_length=20, verbose_name='Тип документа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На согласовании'), ('sent', 'Отправлен'), ('signed', 'Подписан'), ('paid', 'Оплачен'), ('archived', 'Архив')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Дата документа')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USDT', 'USDT')], default='RUB', max_length=10, verbose_name='Валюта')),
                ('payment_terms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок оплаты, дней')),
                ('include_delivery', models.BooleanField(default=False, verbose_name='Включать доставку')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('vat_rate', models.CharField(default='none', max_length=20, verbose_name='НДС')),
                ('vat_mode', models.CharField(default='included', max_length=20, verbose_name='Режим НДС')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=6, verbose_name='Наценка, %')),
                ('markup_mode', models.CharField(default='per_item', max_length=30, verbose_name='Режим наценки')),
                ('markup_calc_mode', models.CharField(default='simple', max_length=30, verbose_name='Формула наценки')),
                ('subject', models.TextField(blank=True, verbose_name='Предмет документа')),
                ('counterparty_name', models.CharField(blank=True, max_length=255, verbose_name='Контрагент')),
                ('counterparty_email', models.EmailField(blank=True, max_length=254, verbose_name='Email контрагента')),
                ('counterparty_phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон контрагента')),
                ('counterparty_inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН контрагента')),
                ('counterparty_kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП контрагента')),
                ('counterparty_ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН контрагента')),
                ('counterparty_ogrnip', models.CharField(blank=True, max_length=20, verbose_name='ОГРНИП контрагента')),
                ('counterparty_address', models.TextField(blank=True, verbose_name='Адрес контрагента')),
                ('counterparty_data', models.JSONField(blank=True, default=dict, verbose_name='Снимок контрагента')),
                ('document_data', models.JSONField(blank=True, default=dict, verbose_name='Данные документа')),
                ('invoice_data', models.JSONField(blank=True, default=dict, verbose_name='Данные счета')),
                ('html_snapshot', models.TextField(blank=True, verbose_name='HTML снапшот')),
                ('snapshot_css', models.TextField(blank=True, verbose_name='CSS снапшота')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Документ договора',
                'verbose_name_plural': 'Документы договоров',
                'ordering': ['-issue_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Legacy ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('document_type', models.CharField(choices=[('contract', 'Договор'), ('invoice', 'Счет'), ('act', 'Акт'), ('appendix', 'Приложение'), ('offer', 'Оферта / КП'), ('other', 'Другое')], default='contract', max_length=20, verbose_name='Тип документа')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Версия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('content_html', models.TextField(blank=True, verbose_name='HTML шаблона')),
                ('css_text', models.TextField(blank=True, verbose_name='CSS шаблона')),
                ('variables_schema', models.JSONField(blank=True, default=list, verbose_name='Переменные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Шаблон договора',
                'verbose_name_plural': 'Шаблоны договоров',
                'ordering': ['-is_active', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(blank=True, max_length=32, verbose_name='Способ доставки')),
                ('tracking_number', models.CharField(blank=True, max_length=120, verbose_name='Трек')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Готовится'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Позиция отгрузки',
                'verbose_name_plural': 'Позиции отгрузки',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='reservationitem',
            name='manager_reservation_item_unique_without_variant',
        ),
        migrations.RemoveConstraint(
            model_name='reservationitem',
            name='manager_reservation_item_unique_with_variant',
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_items', to='manager_portal.purchaseitem', verbose_name='Позиция закупки'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_links', to='orders.orderitem', verbose_name='Строка заказа'),
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_links', to='orders.orderitem', verbose_name='Строка заказа'),
        ),
        migrations.AlterField(
            model_name='managerdeal',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Оплачено клиентом'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='manager_portal.contractcompanyprofile', verbose_name='Профиль компании'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_documents', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='linked_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_documents', to='orders.order', verbose_name='Заказ сайта'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='manager_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_documents', to='manager_portal.managerclient', verbose_name='Клиент кабинета'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='responsible_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_contract_documents', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='manager_portal.contracttemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='manager_portal.managerclient', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_shipments', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='manager_portal.reservation', verbose_name='Резерв'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_shipments', to='manager_portal.warehouse', verbose_name='Склад-источник'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_shipments', to='manager_portal.warehouse', verbose_name='Склад назначения'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_items', to='orders.orderitem', verbose_name='Строка заказа'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_shipment_items', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='reservation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_items', to='manager_portal.reservationitem', verbose_name='Строка резерва'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manager_portal.shipment', verbose_name='Отгрузка'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_shipment_items', to='catalog.productvariant', verbose_name='Вариант'),
        ),
        migrations.RunPython(import_docuflow_legacy_data, migrations.RunPython.noop),
    ]
