# Generated by Django 6.0.1 on 2026-03-10 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_finance_access_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in ('manager_portal_finance_operator', 'manager_portal_finance_admin'):
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('manager_portal', '0005_contractcompanyprofile_contractdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(choices=[('docuflow', 'legacy DocuFlow'), ('business_finance', 'legacy BusinessFinance'), ('site_sqlite', 'legacy site SQLite')], db_index=True, max_length=40, verbose_name='Источник')),
                ('source_ref', models.CharField(max_length=500, verbose_name='Источник данных')),
                ('dry_run', models.BooleanField(db_index=True, default=True, verbose_name='Только проверка')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Завершен'), ('failed', 'Ошибка')], db_index=True, default='running', max_length=20, verbose_name='Статус')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='Сводка')),
                ('error_text', models.TextField(blank=True, verbose_name='Ошибка')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Старт')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
            ],
            options={
                'verbose_name': 'Пакет legacy-импорта',
                'verbose_name_plural': 'Пакеты legacy-импорта',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='managerdeal',
            name='reservation',
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='manager_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_documents', to='manager_portal.managerdeal', verbose_name='Связанная сделка'),
        ),
        migrations.AddField(
            model_name='financedeal',
            name='manager_deal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_deal', to='manager_portal.managerdeal', verbose_name='Связанная сделка'),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='manager_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses', to='manager_portal.managerdeal', verbose_name='Связанная сделка'),
        ),
        migrations.AddField(
            model_name='financepayout',
            name='manager_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payouts', to='manager_portal.managerdeal', verbose_name='Связанная сделка'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Назначен'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_manager_deals', to=settings.AUTH_USER_MODEL, verbose_name='Назначил'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='case_status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('in_progress', 'В работе'), ('waiting_client', 'Ждет клиента'), ('ready_to_ship', 'Готова к отправке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], db_index=True, default='new', max_length=32, verbose_name='Главный этап сделки'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='delivery_status',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('preparing', 'Подготовка'), ('ready', 'Готово'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено')], db_index=True, default='not_required', max_length=20, verbose_name='Состояние доставки'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='documents_status',
            field=models.CharField(choices=[('not_required', 'Не требуются'), ('draft', 'Черновик'), ('sent', 'Отправлены'), ('signed', 'Подписаны')], db_index=True, default='not_required', max_length=20, verbose_name='Состояние документов'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='fulfillment_status',
            field=models.CharField(choices=[('not_reserved', 'Без резерва'), ('reserved_stock', 'Резерв со склада'), ('reserved_incoming', 'Резерв из incoming'), ('procurement_required', 'Нужна закупка'), ('fulfilled', 'Исполнено')], db_index=True, default='not_reserved', max_length=32, verbose_name='Состояние обеспечения'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='next_step_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Следующий шаг'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='next_step_overridden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Переопределен следующий шаг'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='next_step_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_manager_deals', to=settings.AUTH_USER_MODEL, verbose_name='Переопределил следующий шаг'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='next_step_reason_snapshot',
            field=models.TextField(blank=True, verbose_name='Причина следующего шага'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='next_step_source',
            field=models.CharField(choices=[('system', 'Система'), ('manual', 'Ручное управление')], db_index=True, default='system', max_length=20, verbose_name='Источник следующего шага'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='payment_state',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('partial', 'Частичная оплата'), ('paid', 'Оплачено'), ('refunded', 'Возврат')], db_index=True, default='unpaid', max_length=20, verbose_name='Состояние оплаты'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='primary_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_deal', to='manager_portal.reservation', verbose_name='Основной резерв'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='problem_flags',
            field=models.JSONField(blank=True, default=list, verbose_name='Проблемные флаги'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='sla_breached_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='SLA нарушен'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='SLA до'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='manager_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='manager_portal.managerdeal', verbose_name='Связанная сделка'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='manager_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='manager_portal.managerdeal', verbose_name='Связанная сделка'),
        ),
        migrations.AlterField(
            model_name='managerdeal',
            name='deal_status',
            field=models.CharField(choices=[('new_request', 'Новая заявка'), ('awaiting_prepayment', 'Ожидает предоплату'), ('prepayment_received', 'Предоплата получена'), ('supplier_ordered', 'Заказ размещен у поставщика'), ('in_transit', 'Товар в пути'), ('received', 'Товар поступил'), ('ready_to_ship', 'Готов к отправке'), ('shipped', 'Отправлен'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('new', 'Новая'), ('reserved', 'Резерв создан'), ('awaiting_payment', 'Ожидает оплату'), ('paid', 'Оплачена'), ('assembling', 'Собирается'), ('awaiting_evaluation', 'Ожидает оценку'), ('evaluated', 'Оценено'), ('terms_agreed', 'Условия согласованы'), ('awaiting_device_shipment', 'Ожидает отправку устройства клиентом'), ('device_received', 'Устройство получено'), ('inspected', 'Проверено'), ('ready_for_exchange', 'Готово к обмену'), ('topup_received', 'Доплата получена'), ('new_item_shipped', 'Новый товар отправлен'), ('correspondence', 'Переписка'), ('booked', 'Бронь'), ('confirmed', 'Подтверждена'), ('received_by_customer', 'Получена')], db_index=True, default='new', max_length=40, verbose_name='Legacy статус сделки'),
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=80, verbose_name='Тип события')),
                ('source', models.CharField(choices=[('system', 'Система'), ('user', 'Пользователь')], db_index=True, default='system', max_length=20, verbose_name='Источник')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_deal_activities', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('manager_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='manager_portal.managerdeal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Активность сделки',
                'verbose_name_plural': 'Активности сделки',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LegacyImportConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(choices=[('docuflow', 'legacy DocuFlow'), ('business_finance', 'legacy BusinessFinance'), ('site_sqlite', 'legacy site SQLite')], db_index=True, max_length=40, verbose_name='Источник')),
                ('source_model', models.CharField(db_index=True, max_length=120, verbose_name='Таблица источника')),
                ('source_pk', models.CharField(db_index=True, max_length=120, verbose_name='PK источника')),
                ('target_model', models.CharField(blank=True, max_length=120, verbose_name='Целевая модель')),
                ('target_pk', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='PK цели')),
                ('conflict_type', models.CharField(db_index=True, max_length=80, verbose_name='Тип конфликта')),
                ('message', models.TextField(verbose_name='Описание')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Снимок источника')),
                ('target_payload', models.JSONField(blank=True, default=dict, verbose_name='Снимок цели')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='manager_portal.legacyimportbatch', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Конфликт legacy-импорта',
                'verbose_name_plural': 'Конфликты legacy-импорта',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DealSavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('query_string', models.TextField(blank=True, verbose_name='Query string')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_deal_saved_views', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сохраненный вид сделок',
                'verbose_name_plural': 'Сохраненные виды сделок',
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='manager_deal_saved_view_owner_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='LegacyImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(choices=[('docuflow', 'legacy DocuFlow'), ('business_finance', 'legacy BusinessFinance'), ('site_sqlite', 'legacy site SQLite')], db_index=True, max_length=40, verbose_name='Источник')),
                ('source_model', models.CharField(db_index=True, max_length=120, verbose_name='Таблица источника')),
                ('source_pk', models.CharField(db_index=True, max_length=120, verbose_name='PK источника')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('matched', 'Совпало'), ('enriched', 'Дополнено'), ('skipped', 'Пропущено')], db_index=True, max_length=20, verbose_name='Результат')),
                ('target_model', models.CharField(blank=True, max_length=120, verbose_name='Целевая модель')),
                ('target_pk', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='PK цели')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Снимок источника')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='manager_portal.legacyimportbatch', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Запись legacy-импорта',
                'verbose_name_plural': 'Записи legacy-импорта',
                'ordering': ['source_system', 'source_model', 'source_pk'],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_model', 'source_pk'), name='manager_legacyimportrecord_source_unique')],
            },
        ),
        migrations.RunPython(ensure_finance_access_groups, migrations.RunPython.noop),
    ]
