# Generated by Django 6.0.1 on 2026-03-11 20:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_portal', '0008_merge_0007_inventorybalance_min_stock_0007_warehouse_public_stock_synced_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financedeal',
            name='expected_margin_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Ожидаемая маржа сделки'),
        ),
        migrations.AddField(
            model_name='financedeal',
            name='linked_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_deals', to='manager_portal.contractdocument', verbose_name='Связанный документ'),
        ),
        migrations.AddField(
            model_name='financedeal',
            name='payment_method',
            field=models.CharField(blank=True, max_length=32, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='financedeal',
            name='payment_state',
            field=models.CharField(blank=True, max_length=32, verbose_name='Платежный статус заказа'),
        ),
        migrations.AddField(
            model_name='financedeal',
            name='responsible_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_finance_deals', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AddField(
            model_name='financedeal',
            name='snapshot_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Снимок финкейса'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_payer',
            field=models.CharField(blank=True, choices=[('client', 'Клиент'), ('seller', 'Продавец'), ('included', 'Включена в цену')], max_length=20, verbose_name='Кто оплачивает доставку'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='planned_receipt_at',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата получения'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Телефон получателя'),
        ),
    ]
