# Generated by Django 6.0.1 on 2026-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_portal', '0009_financedeal_expected_margin_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='short_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткий ярлык'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее название'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='short_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткий ярлык'),
        ),
        migrations.AddField(
            model_name='financedeal',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Код финкейса'),
        ),
        migrations.AddField(
            model_name='financedeal',
            name='short_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткий ярлык'),
        ),
        migrations.AddField(
            model_name='financedeal',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее название'),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Код расхода'),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='short_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткий ярлык'),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее название'),
        ),
        migrations.AddField(
            model_name='financepayout',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Код выплаты'),
        ),
        migrations.AddField(
            model_name='financepayout',
            name='short_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткий ярлык'),
        ),
        migrations.AddField(
            model_name='financepayout',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее название'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Код сделки'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='short_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткий ярлык'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее название'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Код закупки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='short_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткий ярлык'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее название'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Код брони'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='short_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткий ярлык'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее название'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Код отгрузки'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='short_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткий ярлык'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее название'),
        ),
        migrations.AddField(
            model_name='transportleg',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='Код этапа'),
        ),
        migrations.AddField(
            model_name='transportleg',
            name='short_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткий ярлык'),
        ),
        migrations.AddField(
            model_name='transportleg',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рабочее название'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_number',
            field=models.CharField(blank=True, max_length=120, unique=True, verbose_name='Номер груза'),
        ),
    ]
