# Generated by Django 6.0.1 on 2026-03-12 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_portal', '0011_backfill_identity_fields'),
        ('orders', '0017_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdeal',
            name='delivery_provider_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Перевозчик / провайдер доставки'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_provider_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Перевозчик / провайдер доставки'),
        ),
        migrations.AlterField(
            model_name='legacyimportbatch',
            name='source_system',
            field=models.CharField(choices=[('docuflow', 'legacy DocuFlow'), ('business_finance', 'legacy BusinessFinance'), ('site_sqlite', 'legacy site SQLite'), ('tabular_sales', 'tabular manager sales')], db_index=True, max_length=40, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='legacyimportconflict',
            name='source_system',
            field=models.CharField(choices=[('docuflow', 'legacy DocuFlow'), ('business_finance', 'legacy BusinessFinance'), ('site_sqlite', 'legacy site SQLite'), ('tabular_sales', 'tabular manager sales')], db_index=True, max_length=40, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='legacyimportrecord',
            name='source_system',
            field=models.CharField(choices=[('docuflow', 'legacy DocuFlow'), ('business_finance', 'legacy BusinessFinance'), ('site_sqlite', 'legacy site SQLite'), ('tabular_sales', 'tabular manager sales')], db_index=True, max_length=40, verbose_name='Источник'),
        ),
        migrations.CreateModel(
            name='ManagerPersonAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True, verbose_name='Отображаемое имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_person_aliases', to=settings.AUTH_USER_MODEL, verbose_name='Связанный пользователь')),
            ],
            options={
                'verbose_name': 'Алиас участника сделки',
                'verbose_name_plural': 'Алиасы участников сделки',
                'ordering': ['display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManagerDealParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('answered', 'Ответил'), ('shipped', 'Отправил'), ('item_owner', 'Владелец позиции'), ('planned_profit_share', 'Плановое распределение маржи')], db_index=True, max_length=32, verbose_name='Роль')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма')),
                ('quantity_basis', models.PositiveIntegerField(blank=True, null=True, verbose_name='База по количеству')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('manager_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='manager_portal.managerdeal', verbose_name='Сделка')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_deal_participants', to='orders.orderitem', verbose_name='Строка заказа')),
                ('person_alias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_participations', to='manager_portal.managerpersonalias', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник / начисление сделки',
                'verbose_name_plural': 'Участники / начисления сделки',
                'ordering': ['manager_deal_id', 'role', 'id'],
            },
        ),
    ]
