# Generated by Django 6.0.1 on 2026-03-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_portal', '0012_managerdeal_delivery_provider_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdeal',
            name='returned_to_stock_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Возврат на склад подтвержден'),
        ),
        migrations.AlterField(
            model_name='managerdeal',
            name='deal_status',
            field=models.CharField(choices=[('new_request', 'Новая заявка'), ('awaiting_prepayment', 'Ожидает предоплату'), ('prepayment_received', 'Предоплата получена'), ('supplier_ordered', 'Заказ размещен у поставщика'), ('in_transit', 'Товар в пути'), ('received', 'Товар поступил'), ('ready_to_ship', 'Готов к отправке'), ('shipped', 'Отправлен'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('new', 'Новая'), ('reserved', 'Резерв создан'), ('awaiting_payment', 'Ожидает оплату'), ('paid', 'Оплачена'), ('assembling', 'Собирается'), ('awaiting_evaluation', 'Ожидает оценку'), ('evaluated', 'Оценено'), ('terms_agreed', 'Условия согласованы'), ('awaiting_device_shipment', 'Ожидает отправку устройства клиентом'), ('device_received', 'Устройство получено'), ('inspected', 'Проверено'), ('ready_for_exchange', 'Готово к обмену'), ('topup_received', 'Доплата получена'), ('new_item_shipped', 'Новый товар отправлен'), ('correspondence', 'Переписка'), ('booked', 'Бронь'), ('confirmed', 'Подтверждена'), ('received_by_customer', 'Выдано'), ('returned', 'Возврат')], db_index=True, default='new', max_length=40, verbose_name='Legacy статус сделки'),
        ),
    ]
