# Generated by Django 6.0.1 on 2026-03-17 00:00

from decimal import Decimal

from django.db import migrations, models


def estimate_last_payment_at_for_backfill(manager_deal, activities):
    if Decimal(manager_deal.prepayment_amount or 0) <= 0:
        return None
    for activity in activities:
        payload = activity.payload or {}
        if activity.event_type == 'workflow.recomputed' and payload.get('payment_state'):
            return activity.created_at
    return manager_deal.updated_at


def backfill_last_payment_at(apps, schema_editor):
    ManagerDeal = apps.get_model('manager_portal', 'ManagerDeal')
    DealActivity = apps.get_model('manager_portal', 'DealActivity')

    deals = ManagerDeal.objects.filter(prepayment_amount__gt=0, last_payment_at__isnull=True).only(
        'id',
        'prepayment_amount',
        'updated_at',
    )
    for deal in deals.iterator():
        activities = DealActivity.objects.filter(
            manager_deal_id=deal.pk,
            event_type='workflow.recomputed',
        ).only('event_type', 'payload', 'created_at').order_by('-created_at', '-id')
        last_payment_at = estimate_last_payment_at_for_backfill(deal, activities)
        if last_payment_at is not None:
            ManagerDeal.objects.filter(pk=deal.pk).update(last_payment_at=last_payment_at)


class Migration(migrations.Migration):

    dependencies = [
        ('manager_portal', '0013_managerdeal_returned_to_stock_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdeal',
            name='last_payment_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего платежа'),
        ),
        migrations.RunPython(backfill_last_payment_at, migrations.RunPython.noop),
    ]
