# Generated by Django 6.0.1 on 2026-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_portal', '0014_managerdeal_last_payment_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdeal',
            name='business_bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='business_bik',
            field=models.CharField(blank=True, max_length=20, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='business_checking_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер счёта'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='business_correspondent_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Корр. счёт банка'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='business_telegram',
            field=models.CharField(blank=True, max_length=120, verbose_name='Telegram юр. лица'),
        ),
        migrations.AddField(
            model_name='managerdeal',
            name='business_whatsapp',
            field=models.CharField(blank=True, max_length=120, verbose_name='WhatsApp юр. лица'),
        ),
    ]
