# Generated by Django 6.0.1 on 2026-03-25 23:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_portal', '0015_managerdeal_business_bank_name_and_more'),
        ('orders', '0021_order_contact_channel_order_contact_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financedeal',
            name='distribution_scheme_name_snapshot',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название схемы распределения'),
        ),
        migrations.AddField(
            model_name='financedeal',
            name='distribution_scheme_version_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Версия схемы распределения'),
        ),
        migrations.CreateModel(
            name='FinanceDealLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product_name', models.CharField(max_length=255, verbose_name='Товар')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Себестоимость за единицу')),
                ('unit_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Продажа за единицу')),
                ('line_status', models.CharField(blank=True, max_length=120, verbose_name='Статус')),
                ('delivery_status', models.CharField(blank=True, max_length=120, verbose_name='Доставка')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('finance_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manager_portal.financedeal', verbose_name='Финансовая сделка')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_deal_lines', to='orders.orderitem', verbose_name='Строка заказа')),
                ('owner_alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_deal_lines', to='manager_portal.managerpersonalias', verbose_name='Владелец строки')),
            ],
            options={
                'verbose_name': 'Финансы: строка сделки',
                'verbose_name_plural': 'Финансы: строки сделки',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceDistributionScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название схемы')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Активна')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Финансы: схема распределения',
                'verbose_name_plural': 'Финансы: схемы распределения',
                'ordering': ['name', '-version', 'id'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='manager_finance_distribution_scheme_name_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='FinanceDistributionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('rule_type', models.CharField(choices=[('percent_owner_margin', 'Процент от маржи владельца строк'), ('percent_total_margin', 'Процент от общей маржи'), ('percent_remainder_after_rule', 'Процент от остатка после правила'), ('equal_split_remainder', 'Равная доля остатка')], db_index=True, max_length=40, verbose_name='Тип правила')),
                ('percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='Процент / коэффициент')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner_alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_distribution_owner_rules', to='manager_portal.managerpersonalias', verbose_name='Владелец строк')),
                ('participant_alias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_distribution_rules', to='manager_portal.managerpersonalias', verbose_name='Участник')),
                ('reference_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_rules', to='manager_portal.financedistributionrule', verbose_name='Опорное правило')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='manager_portal.financedistributionscheme', verbose_name='Схема')),
            ],
            options={
                'verbose_name': 'Финансы: правило распределения',
                'verbose_name_plural': 'Финансы: правила распределения',
                'ordering': ['scheme_id', 'position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='financedeal',
            name='distribution_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_deals', to='manager_portal.financedistributionscheme', verbose_name='Схема распределения'),
        ),
        migrations.CreateModel(
            name='FinanceDealShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name_snapshot', models.CharField(max_length=255, verbose_name='Имя участника')),
                ('calculation_type', models.CharField(blank=True, max_length=40, verbose_name='Тип расчета')),
                ('formula_label', models.CharField(blank=True, max_length=255, verbose_name='Пояснение формулы')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='База расчета')),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Рассчитанная сумма')),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Итоговая сумма')),
                ('quantity_basis', models.PositiveIntegerField(blank=True, null=True, verbose_name='База по количеству')),
                ('breakdown', models.JSONField(blank=True, default=dict, verbose_name='Расшифровка')),
                ('is_manual_override', models.BooleanField(default=False, verbose_name='Ручная корректировка')),
                ('manual_amount_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ручная сумма')),
                ('rule_params_override', models.JSONField(blank=True, default=dict, verbose_name='Переопределение параметров правила')),
                ('scheme_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='Название схемы')),
                ('scheme_version_snapshot', models.PositiveIntegerField(blank=True, null=True, verbose_name='Версия схемы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('finance_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='manager_portal.financedeal', verbose_name='Финансовая сделка')),
                ('participant_alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_deal_shares', to='manager_portal.managerpersonalias', verbose_name='Участник')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_shares', to='manager_portal.financedistributionrule', verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Финансы: доля участника',
                'verbose_name_plural': 'Финансы: доли участников',
                'ordering': ['finance_deal_id', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('participant_alias__isnull', False)), fields=('finance_deal', 'participant_alias'), name='manager_finance_deal_share_finance_deal_participant_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='financedistributionrule',
            constraint=models.UniqueConstraint(fields=('scheme', 'participant_alias'), name='manager_finance_distribution_rule_scheme_participant_unique'),
        ),
    ]
