# Generated by Django 6.0.1 on 2026-03-26 09:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def backfill_finance_deal_line_catalog_and_cost_fields(apps, schema_editor):
    FinanceDealLine = apps.get_model('manager_portal', 'FinanceDealLine')

    for line in FinanceDealLine.objects.select_related('order_item').all().iterator():
        update_fields = []

        if line.order_item_id:
            if line.product_id != line.order_item.product_id:
                line.product_id = line.order_item.product_id
                update_fields.append('product')
            if line.variant_id != line.order_item.variant_id:
                line.variant_id = line.order_item.variant_id
                update_fields.append('variant')
            if not (line.product_name or '').strip() and (line.order_item.product_name or '').strip():
                line.product_name = line.order_item.product_name
                update_fields.append('product_name')

        line_type = 'catalog' if line.product_id else 'custom'
        if line.line_type != line_type:
            line.line_type = line_type
            update_fields.append('line_type')

        planned_unit_cost = line.planned_unit_cost or Decimal('0')
        if planned_unit_cost == 0 and line.unit_cost_price:
            line.planned_unit_cost = line.unit_cost_price
            planned_unit_cost = line.planned_unit_cost
            update_fields.append('planned_unit_cost')

        cost_status = 'planned' if planned_unit_cost > 0 else 'none'
        if line.cost_status != cost_status:
            line.cost_status = cost_status
            update_fields.append('cost_status')

        if update_fields:
            line.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_remove_product_shipping_height_cm_and_more'),
        ('manager_portal', '0017_seed_default_finance_distribution_scheme'),
        ('orders', '0021_order_contact_channel_order_contact_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_qty', models.PositiveIntegerField(verbose_name='Получено')),
                ('remaining_qty', models.PositiveIntegerField(verbose_name='Остаток в лоте')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Себестоимость за единицу')),
                ('unit_cost_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Базовая себестоимость за единицу')),
                ('unit_cost_final', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Итоговая себестоимость за единицу')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата приемки')),
                ('reference_type', models.CharField(blank=True, max_length=40, verbose_name='Тип документа')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Лот склада',
                'verbose_name_plural': 'Лоты склада',
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SaleLineAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_qty', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('shipped_qty', models.PositiveIntegerField(default=0, verbose_name='Отгружено')),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Снимок себестоимости')),
                ('status', models.CharField(choices=[('reserved', 'Зарезервировано'), ('shipped', 'Отгружено'), ('released', 'Освобождено')], db_index=True, default='reserved', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Аллокация строки сделки',
                'verbose_name_plural': 'Аллокации строк сделки',
                'ordering': ['order_item_id', 'inventory_lot_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='financedealline',
            name='actual_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Фактическая себестоимость за единицу'),
        ),
        migrations.AddField(
            model_name='financedealline',
            name='cost_status',
            field=models.CharField(choices=[('none', 'Нет'), ('planned', 'План'), ('actual', 'Факт')], db_index=True, default='none', max_length=16, verbose_name='Статус себестоимости'),
        ),
        migrations.AddField(
            model_name='financedealline',
            name='custom_sku',
            field=models.CharField(blank=True, max_length=64, verbose_name='Произвольный SKU'),
        ),
        migrations.AddField(
            model_name='financedealline',
            name='line_type',
            field=models.CharField(choices=[('catalog', 'Каталог'), ('custom', 'Произвольный товар')], db_index=True, default='catalog', max_length=16, verbose_name='Тип строки'),
        ),
        migrations.AddField(
            model_name='financedealline',
            name='planned_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Плановая себестоимость за единицу'),
        ),
        migrations.AddField(
            model_name='financedealline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_finance_lines', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='financedealline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_finance_lines', to='catalog.productvariant', verbose_name='Вариант'),
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='price',
            new_name='unit_cost',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Себестоимость за единицу'),
        ),
        migrations.RunPython(backfill_finance_deal_line_catalog_and_cost_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='financedealline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line_type', 'catalog'), ('product__isnull', False), models.Q(('product_name', ''), _negated=True), ('custom_sku', '')), models.Q(('line_type', 'custom'), ('product__isnull', True), ('variant__isnull', True), models.Q(('product_name', ''), _negated=True)), _connector='OR'), name='finance_line_line_type_integrity'),
        ),
        migrations.AddConstraint(
            model_name='financedealline',
            constraint=models.CheckConstraint(condition=models.Q(('planned_unit_cost__gte', 0)), name='finance_line_planned_unit_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='financedealline',
            constraint=models.CheckConstraint(condition=models.Q(('actual_unit_cost__gte', 0)), name='finance_line_actual_unit_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='purchase_item_unit_cost_gte_zero'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='manager_portal.purchaseitem', verbose_name='Позиция закупки'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='catalog.productvariant', verbose_name='Вариант'),
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='manager_portal.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='salelineallocation',
            name='inventory_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='manager_portal.inventorylot', verbose_name='Лот'),
        ),
        migrations.AddField(
            model_name='salelineallocation',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orders.orderitem', verbose_name='Строка заказа'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty__gt', 0)), name='inventory_lot_received_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_qty__gte', 0)), name='inventory_lot_remaining_qty_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_qty__lte', models.F('received_qty'))), name='inventory_lot_remaining_qty_lte_received_qty'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='inventory_lot_unit_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_base__gte', 0)), name='inventory_lot_unit_cost_base_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_final__gte', 0)), name='inventory_lot_unit_cost_final_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salelineallocation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__gte', 0)), name='sale_line_alloc_reserved_qty_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salelineallocation',
            constraint=models.CheckConstraint(condition=models.Q(('shipped_qty__gte', 0)), name='sale_line_alloc_shipped_qty_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='salelineallocation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__gte', models.F('shipped_qty'))), name='sale_line_alloc_reserved_qty_gte_shipped_qty'),
        ),
        migrations.AddConstraint(
            model_name='salelineallocation',
            constraint=models.UniqueConstraint(fields=('order_item', 'inventory_lot', 'status'), name='sale_line_alloc_order_item_lot_status_unique'),
        ),
    ]
