# Generated by Django 6.0.1 on 2026-05-24 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_normalize_game_sections'),
        ('manager_portal', '0021_merge_dispatch_and_finance_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Приемка'), ('adjustment', 'Корректировка'), ('reserve', 'Резерв'), ('release', 'Снятие резерва'), ('transfer_out', 'Перемещение со склада'), ('transfer_in', 'Перемещение на склад')], max_length=20, verbose_name='Тип движения'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['warehouse', 'product', 'variant', '-created_at'], name='mgr_inv_move_lookup_idx'),
        ),
    ]
