PUBLIC_SITE_FORMS = [
    {
        'endpoint': '/orders/checkout/',
        'form': 'CheckoutForm',
        'template': 'templates/orders/checkout.html',
        'source_type': 'checkout',
        'fields': [
            'first_name',
            'phone',
            'email',
            'contact_channel',
            'contact_handle',
            'delivery_type',
            'city_text',
            'address_line',
            'recipient_name',
            'recipient_phone',
            'comment',
        ],
        'destination': 'Order + SiteLeadRequest + Bitrix deal/contact + product rows',
        'creates_order': True,
        'email_notification': True,
        'anti_spam': True,
    },
    {
        'endpoint': '/orders/purchase-request/create/',
        'form': 'PurchaseRequestForm',
        'template': 'templates/catalog/product_detail.html',
        'source_type': 'purchase_request',
        'fields': ['product_id', 'variant_id', 'source_path', 'phone', 'telegram'],
        'destination': 'PurchaseRequest + SiteLeadRequest + Bitrix deal/contact',
        'creates_order': False,
        'email_notification': True,
        'anti_spam': True,
    },
    {
        'endpoint': '/contacts/',
        'form': 'ContactForm',
        'template': 'templates/contacts.html',
        'source_type': 'contacts',
        'fields': ['name', 'email', 'phone', 'message'],
        'destination': 'ContactRequest + SiteLeadRequest + Bitrix deal/contact',
        'creates_order': False,
        'email_notification': True,
        'anti_spam': True,
    },
    {
        'endpoint': '/arenda/',
        'form': 'CallbackForm',
        'template': 'templates/arenda.html',
        'source_type': 'callback_arenda',
        'fields': ['name', 'phone'],
        'destination': 'CallbackRequest + SiteLeadRequest + Bitrix deal/contact',
        'creates_order': False,
        'email_notification': True,
        'anti_spam': True,
    },
    {
        'endpoint': '/uslugi/',
        'form': 'CallbackForm',
        'template': 'templates/uslugi.html',
        'source_type': 'callback_uslugi',
        'fields': ['name', 'phone'],
        'destination': 'CallbackRequest + SiteLeadRequest + Bitrix deal/contact',
        'creates_order': False,
        'email_notification': True,
        'anti_spam': True,
    },
    {
        'endpoint': '/compact-vr/',
        'form': 'CompactVRForm',
        'template': 'templates/compact_vr.html',
        'source_type': 'compact_vr',
        'fields': ['name', 'contact', 'city', 'format', 'email', 'premises', 'comment'],
        'destination': 'ContactRequest + SiteLeadRequest + Bitrix deal/contact',
        'creates_order': False,
        'email_notification': True,
        'anti_spam': True,
    },
    {
        'endpoint': '/catalog/vr-club-games/',
        'form': 'VRClubQuizForm',
        'template': 'templates/catalog/vr_club_games.html',
        'source_type': 'vr_club',
        'fields': [
            'name',
            'phone',
            'email',
            'club_format',
            'devices',
            'headsets_count',
            'play_places_count',
            'audience',
            'budget',
            'comment',
        ],
        'destination': 'VRClubQuizRequest + SiteLeadRequest + Bitrix deal/contact',
        'creates_order': False,
        'email_notification': False,
        'anti_spam': True,
    },
    {
        'endpoint': '/contacts/',
        'form': 'Standalone GET redirect',
        'template': 'solutions/vr-dlya-kluba/index.html',
        'source_type': 'contacts',
        'fields': ['site_context', 'site_comment', 'name', 'phone', 'email', 'message'],
        'destination': 'Redirect to contacts form, then ContactRequest + SiteLeadRequest + Bitrix',
        'creates_order': False,
        'email_notification': True,
        'anti_spam': False,
    },
    {
        'endpoint': '/contacts/',
        'form': 'Standalone GET redirect',
        'template': 'Конференция (Аттракционы)/index.html',
        'source_type': 'contacts',
        'fields': ['site_context', 'site_comment', 'name', 'phone', 'email', 'message'],
        'destination': 'Redirect to contacts form, then ContactRequest + SiteLeadRequest + Bitrix',
        'creates_order': False,
        'email_notification': True,
        'anti_spam': False,
    },
]
