# Generated by Django 6.0.1 on 2026-01-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_referral_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='kind',
            field=models.CharField(choices=[('topup', 'Пополнение'), ('referral_bonus', 'Бонус за реферала'), ('order_payment', 'Оплата заказа'), ('promo_bonus', 'Бонус по промокоду')], max_length=20, verbose_name='Тип'),
        ),
    ]
