# Generated by Django 6.0.1 on 2026-02-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_commercialproposalcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_policy_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='Версия политики ПД'),
        ),
    ]
