# Generated by Django 6.0.1 on 2026-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_phoneverificationcode_used_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproposalcontact',
            name='email',
            field=models.EmailField(blank=True, help_text='Email менеджера в КП (если нужен).', max_length=254, verbose_name='Email для КП'),
        ),
        migrations.AlterField(
            model_name='commercialproposalcontact',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер, который будет указан в коммерческом предложении в блоке «Телефон для связи». Если не заполнен — подставляется телефон из профиля или общий номер сайта.', max_length=40, verbose_name='Телефон для связи в КП'),
        ),
    ]
