# Generated by Django 6.0.1 on 2026-03-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_commercialproposalcontact_email_and_more'),
        ('accounts', '0012_profile_email_verified_at_and_more'),
    ]

    operations = []

