# Generated by Django 6.0.1 on 2026-03-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
