# Generated by Django 6.0.1 on 2026-03-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='savedaddress',
            name='delivery_type',
            field=models.CharField(choices=[('cdek_pvz', 'CDEK до ПВЗ'), ('courier', 'Курьером'), ('pickup', 'Самовывоз'), ('post', 'Почтой')], max_length=20, verbose_name='Способ доставки'),
        ),
    ]
