# Generated by Django 6.0.1 on 2026-03-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_savedaddress_city_alter_savedaddress_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedaddress',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='savedaddress',
            name='pickup_point',
        ),
    ]
