from copy import deepcopy

LEGAL_BUNDLE_VERSION = '2026-02-23'
LEGAL_UPDATED_AT_DISPLAY = '23 февраля 2026 г.'

LEGAL_DOCS = {
    'privacy': {
        'slug': 'privacy',
        'url_name': 'privacy',
        'template_name': 'legal/privacy.html',
        'title': 'Политика конфиденциальности и обработки персональных данных',
        'short_title': 'Политика конфиденциальности',
        'doc_version': LEGAL_BUNDLE_VERSION,
        'updated_at_display': LEGAL_UPDATED_AT_DISPLAY,
        'summary': 'Порядок сбора, обработки, хранения и защиты персональных данных пользователей сайта BizonVR.',
        'toc': [
            {'id': 'general', 'title': '1. Общие положения'},
            {'id': 'terms', 'title': '2. Термины'},
            {'id': 'operator', 'title': '3. Оператор персональных данных'},
            {'id': 'data', 'title': '4. Перечень данных'},
            {'id': 'goals', 'title': '5. Цели и основания обработки'},
            {'id': 'transfer', 'title': '6. Передача данных третьим лицам'},
            {'id': 'cookies', 'title': '7. Cookies и технические данные'},
            {'id': 'storage', 'title': '8. Хранение и защита'},
            {'id': 'rights', 'title': '9. Права субъекта ПДн'},
            {'id': 'changes', 'title': '10. Изменение политики'},
            {'id': 'contacts', 'title': '11. Контакты'},
        ],
    },
    'oferta': {
        'slug': 'oferta',
        'url_name': 'oferta',
        'template_name': 'legal/public_offer_goods.html',
        'title': 'Публичная оферта о продаже товаров дистанционным способом',
        'short_title': 'Публичная оферта',
        'doc_version': LEGAL_BUNDLE_VERSION,
        'updated_at_display': LEGAL_UPDATED_AT_DISPLAY,
        'summary': 'Условия заключения договора купли-продажи товаров через сайт BizonVR.',
        'toc': [
            {'id': 'offer-general', 'title': '1. Общие положения'},
            {'id': 'subject', 'title': '2. Предмет оферты'},
            {'id': 'order', 'title': '3. Оформление заказа'},
            {'id': 'price-payment', 'title': '4. Цена и оплата'},
            {'id': 'delivery', 'title': '5. Доставка и передача товара'},
            {'id': 'returns', 'title': '6. Возврат и гарантия'},
            {'id': 'liability', 'title': '7. Ответственность'},
            {'id': 'force', 'title': '8. Форс-мажор'},
            {'id': 'offer-details', 'title': '9. Реквизиты продавца'},
        ],
    },
    'user_agreement': {
        'slug': 'user_agreement',
        'url_name': 'user_agreement',
        'template_name': 'legal/user_agreement.html',
        'title': 'Пользовательское соглашение',
        'short_title': 'Пользовательское соглашение',
        'doc_version': LEGAL_BUNDLE_VERSION,
        'updated_at_display': LEGAL_UPDATED_AT_DISPLAY,
        'summary': 'Правила использования сайта BizonVR, личного кабинета и материалов сайта.',
        'toc': [
            {'id': 'ua-general', 'title': '1. Общие условия'},
            {'id': 'ua-account', 'title': '2. Регистрация и аккаунт'},
            {'id': 'ua-rules', 'title': '3. Правила использования'},
            {'id': 'ua-ip', 'title': '4. Интеллектуальная собственность'},
            {'id': 'ua-limits', 'title': '5. Ограничение ответственности'},
            {'id': 'ua-changes', 'title': '6. Изменение соглашения'},
            {'id': 'ua-contacts', 'title': '7. Контакты'},
        ],
    },
    'pd_consent': {
        'slug': 'pd_consent',
        'url_name': 'pd_consent',
        'template_name': 'legal/pd_consent.html',
        'title': 'Согласие на обработку персональных данных',
        'short_title': 'Согласие на обработку ПД',
        'doc_version': LEGAL_BUNDLE_VERSION,
        'updated_at_display': LEGAL_UPDATED_AT_DISPLAY,
        'summary': 'Согласие пользователя на обработку персональных данных при использовании сайта и отправке форм.',
        'toc': [
            {'id': 'consent-subject', 'title': '1. Кто дает согласие'},
            {'id': 'consent-operator', 'title': '2. Оператор'},
            {'id': 'consent-data', 'title': '3. Перечень данных'},
            {'id': 'consent-goals', 'title': '4. Цели обработки'},
            {'id': 'consent-actions', 'title': '5. Действия с данными'},
            {'id': 'consent-term', 'title': '6. Срок действия и отзыв'},
            {'id': 'consent-links', 'title': '7. Связанные документы'},
        ],
    },
    'cookies_policy': {
        'slug': 'cookies_policy',
        'url_name': 'cookies_policy',
        'template_name': 'legal/cookies_policy.html',
        'title': 'Политика использования файлов cookies',
        'short_title': 'Политика cookies',
        'doc_version': LEGAL_BUNDLE_VERSION,
        'updated_at_display': LEGAL_UPDATED_AT_DISPLAY,
        'summary': 'Порядок использования файлов cookies и аналогичных технологий на сайте BizonVR.',
        'toc': [
            {'id': 'cookies-general', 'title': '1. Общие положения'},
            {'id': 'cookies-types', 'title': '2. Какие cookies используются'},
            {'id': 'cookies-goals', 'title': '3. Цели использования'},
            {'id': 'cookies-manage', 'title': '4. Управление cookies'},
            {'id': 'cookies-links', 'title': '5. Связанные документы и контакты'},
        ],
    },
    'sales_terms': {
        'slug': 'sales_terms',
        'url_name': 'sales_terms',
        'template_name': 'legal/sales_terms.html',
        'title': 'Условия оплаты, доставки, возврата и гарантии',
        'short_title': 'Оплата, доставка, возврат',
        'doc_version': LEGAL_BUNDLE_VERSION,
        'updated_at_display': LEGAL_UPDATED_AT_DISPLAY,
        'summary': 'Дополнительные условия исполнения заказов, оплаты, доставки, возврата и гарантийных обязательств.',
        'toc': [
            {'id': 'sales-payment', 'title': '1. Оплата'},
            {'id': 'sales-delivery', 'title': '2. Доставка и самовывоз'},
            {'id': 'sales-acceptance', 'title': '3. Приемка товара'},
            {'id': 'sales-returns', 'title': '4. Возврат и обмен'},
            {'id': 'sales-refunds', 'title': '5. Возврат денежных средств'},
            {'id': 'sales-warranty', 'title': '6. Гарантия'},
            {'id': 'sales-claims', 'title': '7. Претензии и контакты'},
        ],
    },
    'service_request_terms': {
        'slug': 'service_request_terms',
        'url_name': 'service_request_terms',
        'template_name': 'legal/service_request_terms.html',
        'title': 'Условия обработки заявок на аренду и услуги',
        'short_title': 'Условия обработки заявок',
        'doc_version': LEGAL_BUNDLE_VERSION,
        'updated_at_display': LEGAL_UPDATED_AT_DISPLAY,
        'summary': 'Правила обработки информационных заявок с лендингов аренды и услуг BizonVR.',
        'toc': [
            {'id': 'service-nature', 'title': '1. Статус заявки'},
            {'id': 'service-processing', 'title': '2. Порядок обработки заявки'},
            {'id': 'service-channels', 'title': '3. Каналы связи и сроки ответа'},
            {'id': 'service-commercial', 'title': '4. Согласование условий'},
            {'id': 'service-pd', 'title': '5. Персональные данные'},
            {'id': 'service-contacts', 'title': '6. Контакты'},
        ],
    },
}


def get_legal_doc(slug: str):
    doc = LEGAL_DOCS.get(slug)
    if not doc:
        return None
    return deepcopy(doc)
