"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from decouple import Csv, config
from config.env import config_bool

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config_bool('DEBUG', default=True)
ENABLE_ALFATRACK = config_bool('ENABLE_ALFATRACK', default=not DEBUG)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Для HTTPS в продакшене (форма логина, CSRF). Например: https://bizonvr.ru,https://www.bizonvr.ru
CSRF_TRUSTED_ORIGINS = [x.strip() for x in config('CSRF_TRUSTED_ORIGINS', default='').split(',') if x.strip()]


# Application definition

INSTALLED_APPS = [
    'config.apps.ConfigAppConfig',
    'config.apps.ConfigAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'adminsortable2',
    'catalog',
    'accounts',
    'orders',
    'payments',
    'manager_portal',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'catalog.context_processors.catalog_menu',
            ],
            'builtins': [
                'catalog.templatetags.catalog_tags',
                'manager_portal.templatetags.manager_portal_tags',
            ],
            'libraries': {
                'catalog_tags': 'catalog.templatetags.catalog_tags',
            },
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database — только PostgreSQL (одна БД для сайта и админки)
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# DATABASE_URL (postgres://...) или DB_* — оба варианта ведут к одному PostgreSQL.

def _get_postgresql_config():
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='bizon'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }


_db_url = config('DATABASE_URL', default='')
if _db_url:
    import dj_database_url
    _parsed = dj_database_url.parse(_db_url)
    if 'postgresql' in _parsed.get('ENGINE', ''):
        DATABASES = {'default': _parsed}
    else:
        # DATABASE_URL задан, но не PostgreSQL — используем только PostgreSQL из DB_*
        DATABASES = {'default': _get_postgresql_config()}
else:
    DATABASES = {'default': _get_postgresql_config()}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MANAGER_PORTAL_WORKFLOW = {
    'timezone': 'Asia/Yekaterinburg',
    'business_hours': {
        'start': '10:00',
        'end': '19:00',
    },
    'weekdays': [0, 1, 2, 3, 4],
    'stale_after_hours': 48,
    'sla_map': {
        'needs_confirmation': 'created_plus_30m',
        'needs_availability_confirmation': 'current_business_day_end',
        'needs_payment': 'next_business_day_end',
        'needs_reservation': 'current_business_day_end',
        'needs_procurement': 'next_business_day_end',
        'needs_documents': 'current_business_day_end',
        'needs_document_dispatch': 'current_business_day_end',
        'ready_to_ship': 'current_business_day_end',
        'shipped': None,
        'completed': None,
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Лимит отправки SMS: не чаще 1 раза в N секунд с одного номера/IP
SMS_COOLDOWN_SECONDS = 60
SMS_CODE_TTL_MINUTES = 10
EMAIL_CODE_COOLDOWN_SECONDS = config('EMAIL_CODE_COOLDOWN_SECONDS', default=60, cast=int)
EMAIL_CODE_TTL_MINUTES = config('EMAIL_CODE_TTL_MINUTES', default=15, cast=int)
TRUSTED_PROXY_IPS = [x.strip() for x in config('TRUSTED_PROXY_IPS', default='').split(',') if x.strip()]
SMS_PROVIDER = config('SMS_PROVIDER', default='exolve').strip().lower()
EXOLVE_API_KEY = config('EXOLVE_API_KEY', default='').strip()
EXOLVE_SENDER = config('EXOLVE_SENDER', default='').strip()
EXOLVE_API_BASE = config('EXOLVE_API_BASE', default='https://api.exolve.ru/messaging/v1').rstrip('/')
TURNSTILE_SITE_KEY = config('TURNSTILE_SITE_KEY', default='').strip()
TURNSTILE_SECRET_KEY = config('TURNSTILE_SECRET_KEY', default='').strip()
TURNSTILE_VERIFY_URL = config(
    'TURNSTILE_VERIFY_URL',
    default='https://challenges.cloudflare.com/turnstile/v0/siteverify',
).strip()

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/profile/'

# Тестовый режим: после оформления заказ сразу «Оплачен», оплата не требуется.
# В продакшене безопаснее держать выключенным по умолчанию.
TEST_ORDER_NO_PAYMENT = config_bool('TEST_ORDER_NO_PAYMENT', default=False)

# Платёжный провайдер для legacy-интеграции. Без ключа создание платежа не выполняется.
_LEGACY_PAYMENT_ENV_PREFIX = ''.join(['NOW', 'PAYMENTS'])
_LEGACY_PAYMENT_API_BASE = ''.join(['https://api.', 'now', 'payments', '.io/v1'])
PAYMENT_GATEWAY_API_KEY = config(
    'PAYMENT_GATEWAY_API_KEY',
    default=os.getenv(f'{_LEGACY_PAYMENT_ENV_PREFIX}_API_KEY', ''),
)
PAYMENT_GATEWAY_IPN_SECRET = config(
    'PAYMENT_GATEWAY_IPN_SECRET',
    default=os.getenv(f'{_LEGACY_PAYMENT_ENV_PREFIX}_IPN_SECRET', ''),
)
PAYMENT_GATEWAY_API_BASE = config(
    'PAYMENT_GATEWAY_API_BASE',
    default=os.getenv(f'{_LEGACY_PAYMENT_ENV_PREFIX}_API_BASE', _LEGACY_PAYMENT_API_BASE),
)
# Интеграция CDEK widget 3.x
CDEK_WIDGET_ACCOUNT = config('CDEK_WIDGET_ACCOUNT', default='').strip()
CDEK_WIDGET_PASSWORD = config('CDEK_WIDGET_PASSWORD', default='').strip()
CDEK_WIDGET_API_BASE = config('CDEK_WIDGET_API_BASE', default='https://api.cdek.ru/v2').rstrip('/')
# Для IPN webhook и callback нужен абсолютный URL сайта (в продакшене обязательно)
SITE_URL = config('SITE_URL', default='http://localhost:8000').rstrip('/')

# Публичные данные сайта (используются в футере и общих шаблонах)
SITE_BRAND = config('SITE_BRAND', default='BizonVR')
SITE_LOGO = config('SITE_LOGO', default='')  # путь относительно STATIC_URL, напр. images/logo.png
SITE_DESCRIPTION = config('SITE_DESCRIPTION', default='Магазин VR оборудования и аттракционов')
SITE_CONTACT_PHONE = config('SITE_CONTACT_PHONE', default='+7 (932) 491-04-82')
SITE_CONTACT_PHONE_HREF = config('SITE_CONTACT_PHONE_HREF', default='+79324910482')
SITE_CONTACT_EMAIL = config('SITE_CONTACT_EMAIL', default='korrypc@gmail.com')
SITE_CONTACT_ADDRESS = config('SITE_CONTACT_ADDRESS', default='')
SITE_CONTACT_TELEGRAM = config('SITE_CONTACT_TELEGRAM', default='https://t.me/bizon_order_manager')
SITE_CONTACT_TELEGRAM_HANDLE = config('SITE_CONTACT_TELEGRAM_HANDLE', default='@bizon_order_manager')
SITE_AVITO_URL = config(
    'SITE_AVITO_URL',
    default='https://www.avito.ru/user/a933d26a360016c146b6326f33aa18d1/profile/all?src=search_seller_info&iid=7888196703&sellerId=a933d26a360016c146b6326f33aa18d1',
).strip()
SITE_WORK_HOURS = config('SITE_WORK_HOURS', default='Пн-Пт: 10:00-19:00')
SITE_BLOG_URL = config('SITE_BLOG_URL', default='').strip()
SITE_CLUBS_URL = config('SITE_CLUBS_URL', default='').strip()
SITE_INSTRUCTIONS_URL = config('SITE_INSTRUCTIONS_URL', default='').strip()
SITE_YOUTUBE_URL = config('SITE_YOUTUBE_URL', default='https://www.youtube.com/@BIZON-ZON-ZON').strip()
SITE_TIKTOK_URL = config('SITE_TIKTOK_URL', default='https://www.tiktok.com/@bizonvr?_r=1&_t=ZS-94DbHz6YXH3').strip()
DOCUFLOW_BACKEND_URL = config('DOCUFLOW_BACKEND_URL', default='http://127.0.0.1:3001').rstrip('/')

EMAIL_HOST = config('EMAIL_HOST', default='').strip()
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='').strip()
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='').strip()
EMAIL_USE_TLS = config_bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = config_bool('EMAIL_USE_SSL', default=False)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='BizonVR <no-reply@bizonvr.ru>').strip()
CRM_LEADS_EMAIL = config('CRM_LEADS_EMAIL', default='').strip()
EMAIL_VERIFICATION_SUBJECT = config(
    'EMAIL_VERIFICATION_SUBJECT',
    default='Код подтверждения BizonVR',
).strip()
PASSWORD_RESET_EMAIL_SUBJECT = config(
    'PASSWORD_RESET_EMAIL_SUBJECT',
    default='Восстановление пароля BizonVR',
).strip()
PASSWORD_RESET_TIMEOUT = config('PASSWORD_RESET_TIMEOUT', default=15 * 60, cast=int)
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default=(
        'django.core.mail.backends.console.EmailBackend'
        if DEBUG and not EMAIL_HOST
        else 'django.core.mail.backends.smtp.EmailBackend'
    ),
).strip()

# Юридические реквизиты (используются на страницах legal/*)
LEGAL_OPERATOR_FULL_NAME = config(
    'LEGAL_OPERATOR_FULL_NAME',
    default='Индивидуальный предприниматель Едигарьев Ярослав Алексеевич',
)
LEGAL_OPERATOR_SHORT_NAME = config('LEGAL_OPERATOR_SHORT_NAME', default='ИП Едигарьев Я.А.')
LEGAL_OPERATOR_FORM = config('LEGAL_OPERATOR_FORM', default='ИП')
LEGAL_OPERATOR_INN = config('LEGAL_OPERATOR_INN', default='667907832209')
LEGAL_OPERATOR_OGRN = config('LEGAL_OPERATOR_OGRN', default='325665800130159')
LEGAL_OPERATOR_LEGAL_ADDRESS = config('LEGAL_OPERATOR_LEGAL_ADDRESS', default='[ЮРИДИЧЕСКИЙ АДРЕС ИП]')
LEGAL_OPERATOR_POSTAL_ADDRESS = config('LEGAL_OPERATOR_POSTAL_ADDRESS', default='[ПОЧТОВЫЙ АДРЕС ИП]')
LEGAL_OPERATOR_PD_EMAIL = config('LEGAL_OPERATOR_PD_EMAIL', default='korrypc@gmail.com')
LEGAL_SIGNATORY_BASIS = config(
    'LEGAL_SIGNATORY_BASIS',
    default='действует на основании государственной регистрации в качестве индивидуального предпринимателя',
)
LEGAL_BANK_ACCOUNT = config('LEGAL_BANK_ACCOUNT', default='40802810520000666577')
LEGAL_BANK_NAME = config('LEGAL_BANK_NAME', default='ООО "Банк Точка"')
LEGAL_BANK_BIK = config('LEGAL_BANK_BIK', default='044525104')
LEGAL_BANK_INN = config('LEGAL_BANK_INN', default='9721194461')
LEGAL_BANK_CORR_ACCOUNT = config('LEGAL_BANK_CORR_ACCOUNT', default='30101810745374525104')
LEGAL_BANK_LEGAL_ADDRESS = config(
    'LEGAL_BANK_LEGAL_ADDRESS',
    default=(
        '109044, Российская Федерация, г. Москва, вн.тер.г. муниципальный округ '
        'Южнопортовый, пер. 3-й Крутицкий, д. 11, помещ. 7Н'
    ),
)

# Кэш для throttling и прочих краткоживущих данных.
# В продакшене используйте общий backend, например Redis.
_redis_cache_url = config('CACHE_REDIS_URL', default='').strip()
if _redis_cache_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_cache_url,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# WhiteNoise: сжатая статика + manifest-хеши для кэширования в продакшене.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# WhiteNoise cache policy for locally/proxy-served static assets.
WHITENOISE_MAX_AGE = 3600 if DEBUG else 31536000

# Безопасность для продакшена (HTTPS, HSTS, cookies).
# USE_HTTPS=False — локальный HTTP. USE_HTTPS=True — запуск за Nginx с SSL.
_use_https = config_bool('USE_HTTPS', default=False)

# Cross-Origin-Opener-Policy (COOP) - работает только для HTTPS или localhost
# Для разработки на localhost это нормально, для продакшена нужен HTTPS
# Возможные значения: 'same-origin', 'same-origin-allow-popups', 'unsafe-none'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

if not DEBUG:
    SECURE_SSL_REDIRECT = _use_https
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = _use_https
    CSRF_COOKIE_SECURE = _use_https
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_HSTS_SECONDS = 31536000 if _use_https else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
