"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Для HTTPS в продакшене (форма логина, CSRF). Например: https://bizonvr.ru,https://www.bizonvr.ru
CSRF_TRUSTED_ORIGINS = [x.strip() for x in config('CSRF_TRUSTED_ORIGINS', default='').split(',') if x.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog',
    'accounts',
    'orders',
    'payments',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'catalog.context_processors.catalog_menu',
            ],
            'libraries': {
                'catalog_tags': 'catalog.templatetags.catalog_tags',
            },
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database — только PostgreSQL (одна БД для сайта и админки)
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# DATABASE_URL (postgres://...) или DB_* — оба варианта ведут к одному PostgreSQL.

def _get_postgresql_config():
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='bizon'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }


_db_url = config('DATABASE_URL', default='')
if _db_url:
    import dj_database_url
    _parsed = dj_database_url.parse(_db_url)
    if 'postgresql' in _parsed.get('ENGINE', ''):
        DATABASES = {'default': _parsed}
    else:
        # DATABASE_URL задан, но не PostgreSQL — используем только PostgreSQL из DB_*
        DATABASES = {'default': _get_postgresql_config()}
else:
    DATABASES = {'default': _get_postgresql_config()}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Лимит отправки SMS: не чаще 1 раза в N секунд с одного номера/IP
SMS_COOLDOWN_SECONDS = 60
SMS_CODE_TTL_MINUTES = 10

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/profile/'

# Тестовый режим: после оформления заказ сразу «Оплачен», оплата не требуется.
TEST_ORDER_NO_PAYMENT = config('TEST_ORDER_NO_PAYMENT', default='1', cast=bool)

# NowPayments (Фаза 5). Без ключа создание платежа не выполняется.
NOWPAYMENTS_API_KEY = config('NOWPAYMENTS_API_KEY', default='')
NOWPAYMENTS_IPN_SECRET = config('NOWPAYMENTS_IPN_SECRET', default='')
NOWPAYMENTS_API_BASE = config('NOWPAYMENTS_API_BASE', default='https://api.nowpayments.io/v1')
# Для IPN webhook и callback нужен абсолютный URL сайта (в продакшене обязательно)
SITE_URL = config('SITE_URL', default='http://localhost:8000').rstrip('/')

# Кэш для django-ratelimit (ограничение частоты запросов). В продакшене лучше Redis.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Безопасность для продакшена (HTTPS, HSTS, cookies).
# USE_HTTPS=False — без редиректа (Docker, разработка). USE_HTTPS=True — за Nginx с SSL.
_use_https = config('USE_HTTPS', default='0', cast=bool)
if not DEBUG:
    SECURE_SSL_REDIRECT = _use_https
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = _use_https
    CSRF_COOKIE_SECURE = _use_https
    SECURE_HSTS_SECONDS = 31536000 if _use_https else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'