# Generated by Django 6.0.1 on 2026-06-01 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0027_order_metadata_orderitem_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('checkout', 'Корзина / checkout'), ('purchase_request', 'Заявка с карточки товара'), ('contacts', 'Контакты / обратная связь'), ('callback_arenda', 'Обратный звонок / аренда'), ('callback_uslugi', 'Заявка на услуги'), ('compact_vr', 'Compact VR'), ('vr_club', 'VR-клуб'), ('test', 'Тестовая заявка')], db_index=True, max_length=32, verbose_name='Тип источника')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('page_url', models.URLField(blank=True, max_length=500, verbose_name='URL страницы')),
                ('referer', models.URLField(blank=True, max_length=500, verbose_name='Referer')),
                ('utm_source', models.CharField(blank=True, max_length=255, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=255, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=255, verbose_name='UTM campaign')),
                ('utm_content', models.CharField(blank=True, max_length=255, verbose_name='UTM content')),
                ('utm_term', models.CharField(blank=True, max_length=255, verbose_name='UTM term')),
                ('cart_snapshot', models.JSONField(blank=True, default=list, verbose_name='Снимок корзины')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырой payload')),
                ('spam_status', models.CharField(choices=[('clean', 'Чистая'), ('suspicious', 'Подозрительная'), ('spam', 'Спам')], db_index=True, default='clean', max_length=16, verbose_name='Статус антиспама')),
                ('spam_reason', models.TextField(blank=True, verbose_name='Причина антиспама')),
                ('bitrix_entity_type', models.CharField(blank=True, max_length=32, verbose_name='Тип сущности Bitrix')),
                ('bitrix_entity_id', models.CharField(blank=True, max_length=64, verbose_name='ID сущности Bitrix')),
                ('bitrix_contact_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID контакта Bitrix')),
                ('bitrix_deal_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID сделки Bitrix')),
                ('bitrix_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда синхронизирована с Bitrix')),
                ('sync_status', models.CharField(choices=[('pending', 'Ожидает синка'), ('synced', 'Синхронизирована'), ('failed', 'Ошибка синка'), ('skipped', 'Пропущена')], db_index=True, default='pending', max_length=16, verbose_name='Статус синка')),
                ('sync_error', models.TextField(blank=True, verbose_name='Ошибка синка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_lead_requests', to='orders.order', verbose_name='Локальный заказ')),
            ],
            options={
                'verbose_name': 'Аудит заявки с сайта',
                'verbose_name_plural': 'Аудит заявок с сайта',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
