# Generated by Django 6.0.1 on 2026-02-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_fix_product_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='catalog.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Точка выдачи',
                'verbose_name_plural': 'Точки выдачи',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.pickuppoint', verbose_name='Точка выдачи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Остаток в точке',
                'verbose_name_plural': 'Остатки в точках',
                'ordering': ('pickup_point', 'product'),
                'constraints': [models.UniqueConstraint(fields=('product', 'pickup_point'), name='catalog_productstock_product_pickup_unique')],
            },
        ),
    ]
