# Generated by Django 6.0.1 on 2026-02-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
