# Generated by Django 6.0.1 on 2026-02-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_drop_old_bundle_m2m_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbundle',
            name='name',
            field=models.CharField(blank=True, help_text='Для отображения в админке и на странице товара', max_length=200, verbose_name='Название набора'),
        ),
    ]
