# Generated by Django 6.0.1 on 2026-02-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_add_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Характеристика варианта',
                'verbose_name_plural': 'Характеристики варианта',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='productstock',
            name='catalog_productstock_product_pickup_unique',
        ),
        migrations.AddField(
            model_name='productstock',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Пусто — остаток для товаров без вариантов', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.productvariant', verbose_name='Вариант'),
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('product', 'pickup_point', 'variant'), name='catalog_productstock_product_pickup_variant_unique'),
        ),
        migrations.AddField(
            model_name='productvariantcharacteristic',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.productvariant', verbose_name='Вариант'),
        ),
    ]
