# Generated by Django 6.0.1 on 2026-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_add_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsection',
            name='icon',
            field=models.TextField(blank=True, help_text='SVG код иконки для отображения слева от названия раздела', verbose_name='SVG иконка'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, help_text='SVG код иконки для отображения слева от названия категории', verbose_name='SVG иконка'),
        ),
    ]
