# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_category_tile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Счётчик просмотров страницы товара для сортировки по популярности', verbose_name='Просмотры'),
        ),
    ]
