# Generated by Django 6.0.1 on 2026-02-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_bundle_page_and_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='legal_acceptance_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при согласии'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='legal_acceptance_user_agent',
            field=models.CharField(blank=True, max_length=512, verbose_name='User-Agent при согласии'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='legal_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Согласие с юр. документами'),
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='legal_docs_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='Версия юр. документов'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='legal_acceptance_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при согласии'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='legal_acceptance_user_agent',
            field=models.CharField(blank=True, max_length=512, verbose_name='User-Agent при согласии'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='legal_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Согласие с юр. документами'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='legal_docs_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='Версия юр. документов'),
        ),
    ]
