# Generated by Django 6.0.1 on 2026-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_product_can_restore_backup_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbundle',
            name='name',
            field=models.CharField(blank=True, help_text='Отображается на странице набора и в каталоге', max_length=200, verbose_name='Название набора'),
        ),
        migrations.AlterField(
            model_name='productbundleitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Рассчитывается автоматически: −5% от цены товара при покупке полного набора', max_digits=12, null=True, verbose_name='Цена в наборе (₽)'),
        ),
    ]
