# Generated by Django 6.0.1 on 2026-03-10 18:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_productbundle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_height_cm',
            field=models.PositiveIntegerField(default=15, help_text='Используется для расчёта доставки CDEK на один товар.', verbose_name='Высота упаковки, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_length_cm',
            field=models.PositiveIntegerField(default=25, help_text='Используется для расчёта доставки CDEK на один товар.', verbose_name='Длина упаковки, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.500'), help_text='Используется для расчёта доставки CDEK на один товар.', max_digits=7, verbose_name='Вес отправки, кг'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_width_cm',
            field=models.PositiveIntegerField(default=20, help_text='Используется для расчёта доставки CDEK на один товар.', verbose_name='Ширина упаковки, см'),
        ),
    ]
