# Generated by Django 6.0.1 on 2026-03-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_product_shipping_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Используется только для товаров без вариантов. Для variant-first товаров задавайте SKU на уровне варианта.', max_length=64, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SKU'),
        ),
    ]
