# Generated by Django 6.0.1 on 2026-03-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_product_marketplace_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_height_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_length_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_weight_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_width_cm',
        ),
    ]
