# Generated by Django 6.0.1 on 2026-03-30 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_remove_product_shipping_height_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='catalog_cartitem_standalone_unique',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='catalog_cartitem_bundle_unique',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='purchase_mode',
            field=models.CharField(choices=[('stock', 'Из наличия'), ('on_request', 'Под заказ')], default='stock', max_length=20, verbose_name='Режим покупки'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_on_request',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Более низкая цена для покупки под заказ. Если не заполнена, на витрине остаётся только цена из наличия.', max_digits=12, null=True, verbose_name='Цена под заказ'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_on_request_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — использовать цену под заказ у товара.', max_digits=12, null=True, verbose_name='Цена под заказ (переопределение)'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если задана — в корзине используется эта цена вместо текущей цены товара.', max_digits=12, null=True, verbose_name='Цена (override)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена из наличия'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Пусто — использовать цену из наличия у товара.', max_digits=12, null=True, verbose_name='Цена из наличия (переопределение)'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('bundle__isnull', True)), fields=('user', 'product', 'variant', 'purchase_mode'), name='catalog_cartitem_standalone_unique'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('bundle__isnull', False)), fields=('user', 'product', 'variant', 'bundle', 'purchase_mode'), name='catalog_cartitem_bundle_unique'),
        ),
    ]
