# Generated by Django 6.0.1 on 2026-04-01 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_remove_cartitem_catalog_cartitem_standalone_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('source_name', models.CharField(help_text='Точное значение ProductCharacteristic.name, из которого собираются данные фильтра.', max_length=200, unique=True, verbose_name='Исходное имя характеристики')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='Использовать в фильтрах')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Определение характеристики',
                'verbose_name_plural': 'Определения характеристик',
                'ordering': ('sort_order', 'name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='CategoryFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
                ('is_quick_filter', models.BooleanField(default=False, verbose_name='Быстрый фильтр')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_expanded_by_default', models.BooleanField(default=False, verbose_name='Раскрыт по умолчанию')),
                ('show_top_n', models.PositiveIntegerField(blank=True, null=True, verbose_name='Показывать первых N значений')),
                ('hide_single_value', models.BooleanField(default=True, verbose_name='Скрывать при одном значении')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_configs', to='catalog.category', verbose_name='Категория')),
                ('characteristic_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_filter_configs', to='catalog.characteristicdefinition', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Конфиг фильтра категории',
                'verbose_name_plural': 'Конфиги фильтров категорий',
                'ordering': ('category', 'sort_order', 'characteristic_definition__sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('category', 'characteristic_definition'), name='catalog_category_filter_config_unique')],
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValueAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=500, verbose_name='Сырое значение')),
                ('normalized_value', models.CharField(max_length=500, verbose_name='Нормализованное значение')),
                ('display_value', models.CharField(blank=True, max_length=500, verbose_name='Отображаемое значение')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('characteristic_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_aliases', to='catalog.characteristicdefinition', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Алиас значения характеристики',
                'verbose_name_plural': 'Алиасы значений характеристик',
                'ordering': ('characteristic_definition', 'sort_order', 'raw_value'),
                'indexes': [models.Index(fields=['characteristic_definition', 'is_active'], name='catalog_char_val_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('characteristic_definition', 'raw_value'), name='catalog_char_value_alias_unique')],
            },
        ),
        migrations.CreateModel(
            name='SectionFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
                ('is_quick_filter', models.BooleanField(default=False, verbose_name='Быстрый фильтр')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_expanded_by_default', models.BooleanField(default=False, verbose_name='Раскрыт по умолчанию')),
                ('show_top_n', models.PositiveIntegerField(blank=True, null=True, verbose_name='Показывать первых N значений')),
                ('hide_single_value', models.BooleanField(default=True, verbose_name='Скрывать при одном значении')),
                ('characteristic_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_filter_configs', to='catalog.characteristicdefinition', verbose_name='Характеристика')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_configs', to='catalog.catalogsection', verbose_name='Раздел каталога')),
            ],
            options={
                'verbose_name': 'Конфиг фильтра раздела',
                'verbose_name_plural': 'Конфиги фильтров разделов',
                'ordering': ('section', 'sort_order', 'characteristic_definition__sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('section', 'characteristic_definition'), name='catalog_section_filter_config_unique')],
            },
        ),
    ]
