# Generated by Django 6.0.1 on 2026-04-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Показывается в плитках категории. Если не заполнено, используется фото набора или товара.', null=True, upload_to='categories/', verbose_name='Изображение категории'),
        ),
    ]
