# Generated by Django 6.0.1 on 2026-05-06 22:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_game_packs(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    GamePack = apps.get_model('catalog', 'GamePack')
    GamePackEntry = apps.get_model('catalog', 'GamePackEntry')
    GamePackItem = apps.get_model('catalog', 'GamePackItem')
    CartItem = apps.get_model('catalog', 'CartItem')

    product_tag_through = Product.tags.through
    game_pack_tag_through = GamePack.tags.through

    legacy_products = list(
        Product.objects.filter(product_kind='game_pack').prefetch_related('game_pack_items', 'tags')
    )

    for legacy_product in legacy_products:
        game_pack = GamePack.objects.create(
            category_id=legacy_product.category_id,
            name=legacy_product.name,
            slug=legacy_product.slug,
            description=legacy_product.description,
            image=legacy_product.image,
            price=legacy_product.price,
            discount_percent=legacy_product.discount_percent,
            price_on_request=legacy_product.price_on_request,
            is_active=legacy_product.is_active,
            allow_order_on_request=legacy_product.allow_order_on_request,
            views_count=legacy_product.views_count,
            created_at=legacy_product.created_at,
            updated_at=legacy_product.updated_at,
        )

        tag_ids = list(
            product_tag_through.objects.filter(product_id=legacy_product.pk).values_list('producttag_id', flat=True)
        )
        game_pack_tag_through.objects.bulk_create(
            [
                game_pack_tag_through(gamepack_id=game_pack.pk, producttag_id=tag_id)
                for tag_id in tag_ids
            ],
            ignore_conflicts=True,
        )

        for legacy_item in GamePackItem.objects.filter(product_id=legacy_product.pk).order_by('sort_order', 'id'):
            linked_product = (
                Product.objects.filter(name__iexact=legacy_item.title)
                .exclude(product_kind='game_pack')
                .order_by('id')
                .first()
            )
            GamePackEntry.objects.create(
                game_pack_id=game_pack.pk,
                product_id=linked_product.pk if linked_product else None,
                unresolved_title='' if linked_product else legacy_item.title,
                quantity=1,
                note=legacy_item.note,
                sort_order=legacy_item.sort_order,
            )

        CartItem.objects.filter(product_id=legacy_product.pk).update(
            product_id=None,
            variant_id=None,
            bundle_id=None,
            price_override=None,
            game_pack_id=game_pack.pk,
        )
        Product.objects.filter(pk=legacy_product.pk).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0056_product_product_kind_gamepackitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название пака')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_packs/', verbose_name='Изображение')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена из наличия')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %')),
                ('price_on_request', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена под заказ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('allow_order_on_request', models.BooleanField(default=True, verbose_name='Разрешён заказ под запрос')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_packs', to='catalog.category', verbose_name='Игровой раздел')),
                ('tags', models.ManyToManyField(blank=True, related_name='game_packs', to='catalog.producttag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Игровой пак',
                'verbose_name_plural': 'Игровые паки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GamePackEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('unresolved_title', models.CharField(blank=True, max_length=255, verbose_name='Legacy title without Product match')),
                ('game_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='catalog.gamepack', verbose_name='Игровой пак')),
                ('product', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_pack_entries', to='catalog.product', verbose_name='Связанный товар')),
            ],
            options={
                'verbose_name': 'Позиция игрового пака',
                'verbose_name_plural': 'Позиции игрового пака',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['product', 'variant', 'game_pack'], 'verbose_name': 'Позиция корзины', 'verbose_name_plural': 'Позиции корзины'},
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='catalog_cartitem_standalone_unique',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='catalog.productbundle', verbose_name='Набор в корзине'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Используется, если в корзине была сохранена отличающаяся публичная цена.', max_digits=12, null=True, verbose_name='Цена (override)'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='game_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.gamepack', verbose_name='Игровой пак'),
        ),
        migrations.RunPython(migrate_legacy_game_packs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('bundle__isnull', True), ('game_pack__isnull', True)), fields=('user', 'product', 'variant', 'purchase_mode'), name='catalog_cartitem_standalone_unique'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('game_pack__isnull', False)), fields=('user', 'game_pack', 'purchase_mode'), name='catalog_cartitem_game_pack_unique'),
        ),
    ]
