# Generated by Django 6.0.1 on 2026-05-08 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_gamepack_gamepackentry_alter_cartitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGameMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.CharField(blank=True, help_text='Через запятую: Quest, Pico, PCVR', max_length=255, verbose_name='Устройства')),
                ('genres', models.CharField(blank=True, help_text='Через запятую', max_length=255, verbose_name='Жанры')),
                ('min_players', models.PositiveIntegerField(default=1, verbose_name='Минимум игроков')),
                ('max_players', models.PositiveIntegerField(default=1, verbose_name='Максимум игроков')),
                ('age_rating', models.CharField(blank=True, max_length=40, verbose_name='Возраст')),
                ('club_format', models.CharField(blank=True, choices=[('arcade', 'Аркада / ТЦ'), ('club', 'VR-клуб'), ('arena', 'Арена'), ('mobile', 'Выездной формат')], max_length=40, verbose_name='Формат клуба')),
                ('is_pcvr', models.BooleanField(default=False, verbose_name='PCVR')),
                ('is_standalone', models.BooleanField(default=True, verbose_name='Standalone')),
                ('is_multiplayer', models.BooleanField(default=False, verbose_name='Multiplayer')),
                ('b2b_note', models.CharField(blank=True, max_length=255, verbose_name='B2B-смысл')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показывать в конструкторе')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'B2B-метаданные игры',
                'verbose_name_plural': 'B2B-метаданные игр',
                'ordering': ('sort_order', 'product__name'),
            },
        ),
        migrations.CreateModel(
            name='VRClubQuizRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('club_format', models.CharField(blank=True, max_length=120, verbose_name='Формат клуба')),
                ('devices', models.CharField(blank=True, max_length=255, verbose_name='Устройства')),
                ('headsets_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество шлемов')),
                ('play_places_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Игровых мест')),
                ('audience', models.CharField(blank=True, max_length=255, verbose_name='Аудитория')),
                ('budget', models.CharField(blank=True, max_length=120, verbose_name='Бюджет')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('legal_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Согласие с юр. документами')),
                ('legal_docs_version', models.CharField(blank=True, max_length=32, verbose_name='Версия юр. документов')),
                ('legal_acceptance_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при согласии')),
                ('legal_acceptance_user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заявка квиза VR-клуба',
                'verbose_name_plural': 'Заявки квиза VR-клуба',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Состав индивидуального игрового комплекта или служебные данные услуги.', verbose_name='Снапшот произвольной строки'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='line_type',
            field=models.CharField(choices=[('equipment', 'Оборудование'), ('game', 'Игры'), ('service', 'Услуга'), ('custom_game_pack', 'Индивидуальный игровой комплект')], db_index=True, default='equipment', max_length=24, verbose_name='Тип строки'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='age_rating',
            field=models.CharField(blank=True, max_length=40, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='club_format',
            field=models.CharField(blank=True, max_length=120, verbose_name='Формат клуба'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='commercial_pitch',
            field=models.TextField(blank=True, verbose_name='Коммерческий тезис'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='devices',
            field=models.CharField(blank=True, help_text='Через запятую: Quest, Pico, PCVR', max_length=255, verbose_name='Устройства'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='genres',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=255, verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='included_summary',
            field=models.TextField(blank=True, verbose_name='Что входит'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='play_places_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Игровых мест'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='players_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Игроков до'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='show_on_vr_club_page',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Показывать в разделе VR-клубов'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='vr_club_tariff',
            field=models.CharField(blank=True, choices=[('', 'Не тариф'), ('start', 'Старт'), ('club', 'Клуб'), ('maximum', 'Максимум'), ('custom', 'Индивидуальный')], db_index=True, default='', max_length=20, verbose_name='Тариф для VR-клубов'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_vr_club_service',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Услуга для VR-клубов'),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена для корзины'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_kind',
            field=models.CharField(choices=[('general', 'Общая услуга'), ('installation', 'Установка'), ('headset_setup', 'Настройка шлемов'), ('accounts', 'Аккаунты'), ('pcvr', 'PCVR'), ('multiplayer', 'Multiplayer'), ('staff_training', 'Инструкция персоналу'), ('support', 'Поддержка')], db_index=True, default='general', max_length=32, verbose_name='Тип услуги'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('user', 'service'), name='catalog_cartitem_service_unique'),
        ),
        migrations.AddField(
            model_name='productgamemetadata',
            name='product',
            field=models.OneToOneField(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='game_metadata', to='catalog.product', verbose_name='Игра'),
        ),
    ]
