# Generated by Codex on 2026-05-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_productgamemetadata_vrclubquizrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePackServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название услуги вручную')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена в составе пака')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('game_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_entries', to='catalog.gamepack', verbose_name='Игровой пак')),
                ('service', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_pack_entries', to='catalog.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга игрового пака',
                'verbose_name_plural': 'Услуги игрового пака',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
