# Generated by Django 6.0.1 on 2026-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_gamepackserviceentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamepack',
            options={'ordering': ('sort_order', '-created_at'), 'verbose_name': 'Игровой пак', 'verbose_name_plural': 'Игровые паки'},
        ),
        migrations.AddField(
            model_name='gamepack',
            name='package_format',
            field=models.CharField(choices=[('club', 'Для клуба'), ('home', 'Для дома'), ('arena', 'Для арены'), ('kids', 'Для детей'), ('party', 'Для вечеринки')], db_index=True, default='club', max_length=20, verbose_name='Формат пака'),
        ),
        migrations.AddField(
            model_name='gamepack',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='productgamemetadata',
            name='club_format',
            field=models.CharField(blank=True, choices=[('arcade', 'Аркада / ТЦ'), ('club', 'VR-клуб'), ('arena', 'Арена'), ('home', 'Дом'), ('kids', 'Дети'), ('party', 'Вечеринка'), ('mobile', 'Выездной формат')], max_length=40, verbose_name='Формат клуба'),
        ),
    ]
