# Generated by Codex on 2026-05-12

from django.db import migrations, models


FORMAT_ALIASES = {
    'arcade': 'arcade',
    'club': 'club',
    'arena': 'arena',
    'home': 'home',
    'kids': 'kids',
    'party': 'party',
    'mobile': 'mobile',
    'Аркада / ТЦ': 'arcade',
    'VR-клуб': 'club',
    'Арена': 'arena',
    'Дом': 'home',
    'Дети': 'kids',
    'Вечеринка': 'party',
    'Выездной формат': 'mobile',
    'VR-зона': 'club',
}


def normalize_gamepack_club_format(apps, schema_editor):
    GamePack = apps.get_model('catalog', 'GamePack')
    unknown_values = set()

    for game_pack in GamePack.objects.all().only('pk', 'club_format'):
        raw_value = (game_pack.club_format or '').strip()
        if not raw_value:
            if game_pack.club_format != '':
                GamePack.objects.filter(pk=game_pack.pk).update(club_format='')
            continue

        normalized_value = FORMAT_ALIASES.get(raw_value)
        if normalized_value is None:
            unknown_values.add(raw_value)
            continue

        if normalized_value != game_pack.club_format:
            GamePack.objects.filter(pk=game_pack.pk).update(club_format=normalized_value)

    if unknown_values:
        values = ', '.join(sorted(unknown_values))
        raise RuntimeError(f'Unknown GamePack.club_format values: {values}')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_alter_gamepack_options_gamepack_package_format_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_gamepack_club_format, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='gamepack',
            name='club_format',
            field=models.CharField(
                blank=True,
                choices=[
                    ('arcade', 'Аркада / ТЦ'),
                    ('club', 'VR-клуб'),
                    ('arena', 'Арена'),
                    ('home', 'Дом'),
                    ('kids', 'Дети'),
                    ('party', 'Вечеринка'),
                    ('mobile', 'Выездной формат'),
                ],
                max_length=40,
                verbose_name='Формат клуба',
            ),
        ),
    ]
