# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_normalize_gamepack_club_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepack',
            name='mirror_product',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='mirrored_game_pack',
                to='catalog.product',
                verbose_name='Совместимый товар',
            ),
        ),
        migrations.AddField(
            model_name='gamepackentry',
            name='platform',
            field=models.CharField(blank=True, max_length=120, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='gamepackserviceentry',
            name='platform',
            field=models.CharField(blank=True, max_length=120, verbose_name='Платформа'),
        ),
    ]
