# Generated by Django 6.0.1 on 2026-01-30 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_promocode_order_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Скидка по промокоду (₽)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма заказа (до скидки)'),
        ),
    ]
