# Generated by Django 6.0.1 on 2026-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_order_city_pickup_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_decreased',
            field=models.BooleanField(default=False, verbose_name='Остаток списан'),
        ),
    ]
