# Generated by Django 6.0.1 on 2026-03-10 18:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_v1_checkout_and_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cdek_fallback_to_nearest',
            field=models.BooleanField(default=True, verbose_name='Если ПВЗ не найден, отправить в ближайший'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_volume_cm3',
            field=models.PositiveIntegerField(default=0, verbose_name='Объём отправки, см3'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=9, verbose_name='Вес отправки, кг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('cdek_pvz', 'CDEK до ПВЗ'), ('courier', 'Курьером'), ('pickup', 'Самовывоз'), ('post', 'Почтой'), ('negotiable', 'По договорённости')], default='cdek_pvz', max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online_payment', 'Банковская карта'), ('cash_on_delivery', 'Расчёт с менеджером'), ('bank_transfer', 'Перевод по реквизитам'), ('invoice', 'Через менеджера для юрлиц'), ('manager_payment', 'Через менеджера')], default='online_payment', max_length=32, verbose_name='Способ оплаты'),
        ),
    ]
