# Generated by Django 6.0.1 on 2026-03-10 19:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_cdek_fallback_to_nearest_order_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у'), ('refurbished', 'Refurbished')], default='new', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Скидка за единицу'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Закупочная цена за единицу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('cdek_pvz', 'CDEK до ПВЗ'), ('cdek_courier', 'CDEK курьер'), ('courier', 'Курьером'), ('pickup', 'Самовывоз'), ('city_delivery', 'Доставка по городу'), ('other_transport', 'Другая ТК'), ('post', 'Почтой'), ('negotiable', 'По договорённости')], default='cdek_pvz', max_length=20, verbose_name='Способ доставки'),
        ),
    ]
