# Generated by Django 6.0.1 on 2026-03-10 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_product_shipping_height_cm_and_more'),
        ('orders', '0015_orderitem_comment_orderitem_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='Вариант'),
        ),
    ]
