# Generated by Django 6.0.1 on 2026-03-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_card', 'Банковская карта'), ('sbp', 'СБП'), ('manager_payment', 'Для юридических лиц через менеджера'), ('online_payment', 'Банковская карта (архивный способ)'), ('cash_on_delivery', 'Расчёт с менеджером (архивный способ)'), ('bank_transfer', 'Перевод по реквизитам (архивный способ)'), ('invoice', 'Через менеджера для юрлиц (архивный способ)')], default='bank_card', max_length=32, verbose_name='Способ оплаты'),
        ),
    ]
