# Generated by Django 6.0.1 on 2026-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business_bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='order',
            name='business_bik',
            field=models.CharField(blank=True, max_length=20, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='order',
            name='business_checking_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер счёта'),
        ),
        migrations.AddField(
            model_name='order',
            name='business_company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='order',
            name='business_correspondent_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Корр. счёт банка'),
        ),
        migrations.AddField(
            model_name='order',
            name='business_inn',
            field=models.CharField(blank=True, max_length=32, verbose_name='ИНН организации'),
        ),
        migrations.AddField(
            model_name='order',
            name='business_kpp',
            field=models.CharField(blank=True, max_length=32, verbose_name='КПП организации'),
        ),
        migrations.AddField(
            model_name='order',
            name='business_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Телефон юр. лица'),
        ),
        migrations.AddField(
            model_name='order',
            name='business_telegram',
            field=models.CharField(blank=True, max_length=120, verbose_name='Telegram юр. лица'),
        ),
        migrations.AddField(
            model_name='order',
            name='business_whatsapp',
            field=models.CharField(blank=True, max_length=120, verbose_name='WhatsApp юр. лица'),
        ),
    ]
