# Generated by Django 6.0.1 on 2026-03-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderitem_product_image_url_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cdek_fallback_to_nearest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_volume_cm3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_weight_kg',
        ),
    ]
