# Generated by Django 6.0.1 on 2026-03-26 09:58

from decimal import Decimal
from django.db import migrations, models


def backfill_order_item_catalog_and_cost_fields(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')

    for item in OrderItem.objects.all().iterator():
        update_fields = []

        line_type = 'catalog' if item.product_id else 'custom'
        if item.line_type != line_type:
            item.line_type = line_type
            update_fields.append('line_type')

        planned_unit_cost = item.planned_unit_cost or Decimal('0')
        if planned_unit_cost == 0 and item.purchase_price:
            item.planned_unit_cost = item.purchase_price
            planned_unit_cost = item.planned_unit_cost
            update_fields.append('planned_unit_cost')

        cost_status = 'planned' if planned_unit_cost > 0 else 'none'
        if item.cost_status != cost_status:
            item.cost_status = cost_status
            update_fields.append('cost_status')

        if item.product_id and not (item.product_name or '').strip():
            item.product_name = item.product.name
            update_fields.append('product_name')

        if update_fields:
            item.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_remove_product_shipping_height_cm_and_more'),
        ('orders', '0021_order_contact_channel_order_contact_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='actual_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Фактическая себестоимость за единицу'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_status',
            field=models.CharField(choices=[('none', 'Нет'), ('planned', 'План'), ('actual', 'Факт')], db_index=True, default='none', max_length=16, verbose_name='Статус себестоимости'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_sku',
            field=models.CharField(blank=True, help_text='Используется только для произвольных строк сделки.', max_length=64, verbose_name='Произвольный SKU'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_type',
            field=models.CharField(choices=[('catalog', 'Каталог'), ('custom', 'Произвольный товар')], db_index=True, default='catalog', max_length=16, verbose_name='Тип строки'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='planned_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Плановая себестоимость за единицу'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Эффективная себестоимость за единицу'),
        ),
        migrations.RunPython(backfill_order_item_catalog_and_cost_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line_type', 'catalog'), ('product__isnull', False), models.Q(('product_name', ''), _negated=True), ('custom_sku', '')), models.Q(('line_type', 'custom'), ('product__isnull', True), ('variant__isnull', True), models.Q(('product_name', ''), _negated=True)), _connector='OR'), name='order_item_line_type_integrity'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('planned_unit_cost__gte', 0)), name='order_item_planned_unit_cost_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('actual_unit_cost__gte', 0)), name='order_item_actual_unit_cost_gte_zero'),
        ),
    ]
