# Generated by Django 6.0.1 on 2026-05-06 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_gamepack_gamepackentry_alter_cartitem_options_and_more'),
        ('orders', '0025_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='order_item_line_type_integrity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='game_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.gamepack', verbose_name='Игровой пак'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line_type', 'catalog'), models.Q(('product__isnull', False), ('game_pack__isnull', False), _connector='OR'), models.Q(('product_name', ''), _negated=True), ('custom_sku', '')), models.Q(('line_type', 'custom'), ('product__isnull', True), ('game_pack__isnull', True), ('variant__isnull', True), models.Q(('product_name', ''), _negated=True)), _connector='OR'), name='order_item_line_type_integrity'),
        ),
    ]
