# Generated by Django 6.0.1 on 2026-05-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_orderitem_order_item_line_type_integrity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Снапшот состава игрового комплекта или услуги.', verbose_name='Дополнительные данные'),
        ),
    ]
