# Generated by Django 6.0.1 on 2026-05-24 19:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0063_normalize_game_sections'),
        ('manager_portal', '0022_alter_inventorymovement_movement_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_ui_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_ui_outgoing_transfers', to='manager_portal.warehouse', verbose_name='Склад-источник')),
                ('target_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_ui_incoming_transfers', to='manager_portal.warehouse', verbose_name='Склад-получатель')),
            ],
            options={
                'verbose_name': 'Складское перемещение',
                'verbose_name_plural': 'Складские перемещения',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Себестоимость за единицу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_ui_transfer_lines', to='catalog.product', verbose_name='Товар')),
                ('source_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_ui_source_transfer_lines', to='manager_portal.inventorylot', verbose_name='Исходный лот')),
                ('target_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_ui_target_transfer_lines', to='manager_portal.inventorylot', verbose_name='Созданный лот')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse_ui.warehousetransfer', verbose_name='Перемещение')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_ui_transfer_lines', to='catalog.productvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Строка складского перемещения',
                'verbose_name_plural': 'Строки складского перемещения',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['transfer', 'product', 'variant'], name='warehouse_u_transfe_c05f60_idx')],
            },
        ),
    ]
